/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BSDsResponse,
  BadRequest,
  Forbidden,
  InternalError,
  TemporarilyUnavailable,
} from '../models/index';
import {
    BSDsResponseFromJSON,
    BSDsResponseToJSON,
    BadRequestFromJSON,
    BadRequestToJSON,
    ForbiddenFromJSON,
    ForbiddenToJSON,
    InternalErrorFromJSON,
    InternalErrorToJSON,
    TemporarilyUnavailableFromJSON,
    TemporarilyUnavailableToJSON,
} from '../models/index';

/**
 * 
 */
export class BSDsApi extends runtime.BaseAPI {

    /**
     * Fetch all Branded Short Domains
     * Get BSDs
     */
    async getBSDsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BSDsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bsds`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BSDsResponseFromJSON(jsonValue));
    }

    /**
     * Fetch all Branded Short Domains
     * Get BSDs
     */
    async getBSDs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BSDsResponse> {
        const response = await this.getBSDsRaw(initOverrides);
        return await response.value();
    }

}
