/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequest,
    BadRequestFromJSON,
    BadRequestToJSON,
} from '../models/BadRequest';
import {
    type CityMetrics,
    CityMetricsFromJSON,
    CityMetricsToJSON,
} from '../models/CityMetrics';
import {
    type ClickMetrics,
    ClickMetricsFromJSON,
    ClickMetricsToJSON,
} from '../models/ClickMetrics';
import {
    type DeviceMetrics,
    DeviceMetricsFromJSON,
    DeviceMetricsToJSON,
} from '../models/DeviceMetrics';
import {
    type Forbidden,
    ForbiddenFromJSON,
    ForbiddenToJSON,
} from '../models/Forbidden';
import {
    type GetGroupLinkClicksByDevice200Response,
    GetGroupLinkClicksByDevice200ResponseFromJSON,
    GetGroupLinkClicksByDevice200ResponseToJSON,
} from '../models/GetGroupLinkClicksByDevice200Response';
import {
    type GetGroupTopCodeScans200Response,
    GetGroupTopCodeScans200ResponseFromJSON,
    GetGroupTopCodeScans200ResponseToJSON,
} from '../models/GetGroupTopCodeScans200Response';
import {
    type Group,
    GroupFromJSON,
    GroupToJSON,
} from '../models/Group';
import {
    type GroupClicks,
    GroupClicksFromJSON,
    GroupClicksToJSON,
} from '../models/GroupClicks';
import {
    type GroupExportRequestBody,
    GroupExportRequestBodyFromJSON,
    GroupExportRequestBodyToJSON,
} from '../models/GroupExportRequestBody';
import {
    type GroupExportResponse,
    GroupExportResponseFromJSON,
    GroupExportResponseToJSON,
} from '../models/GroupExportResponse';
import {
    type GroupFeatureUsage,
    GroupFeatureUsageFromJSON,
    GroupFeatureUsageToJSON,
} from '../models/GroupFeatureUsage';
import {
    type GroupHistoricalUsage,
    GroupHistoricalUsageFromJSON,
    GroupHistoricalUsageToJSON,
} from '../models/GroupHistoricalUsage';
import {
    type GroupPreferences,
    GroupPreferencesFromJSON,
    GroupPreferencesToJSON,
} from '../models/GroupPreferences';
import {
    type GroupUpdate,
    GroupUpdateFromJSON,
    GroupUpdateToJSON,
} from '../models/GroupUpdate';
import {
    type Groups,
    GroupsFromJSON,
    GroupsToJSON,
} from '../models/Groups';
import {
    type InternalError,
    InternalErrorFromJSON,
    InternalErrorToJSON,
} from '../models/InternalError';
import {
    type Metrics,
    MetricsFromJSON,
    MetricsToJSON,
} from '../models/Metrics';
import {
    type MonthlyLimitExceeded,
    MonthlyLimitExceededFromJSON,
    MonthlyLimitExceededToJSON,
} from '../models/MonthlyLimitExceeded';
import {
    type NotFound,
    NotFoundFromJSON,
    NotFoundToJSON,
} from '../models/NotFound';
import {
    type SortedLinks,
    SortedLinksFromJSON,
    SortedLinksToJSON,
} from '../models/SortedLinks';
import {
    type Tags,
    TagsFromJSON,
    TagsToJSON,
} from '../models/Tags';
import {
    type TemporarilyUnavailable,
    TemporarilyUnavailableFromJSON,
    TemporarilyUnavailableToJSON,
} from '../models/TemporarilyUnavailable';
import {
    type TimeUnit,
    TimeUnitFromJSON,
    TimeUnitToJSON,
} from '../models/TimeUnit';
import {
    type TimeUnitDWM,
    TimeUnitDWMFromJSON,
    TimeUnitDWMToJSON,
} from '../models/TimeUnitDWM';
import {
    type UnprocessableEntity,
    UnprocessableEntityFromJSON,
    UnprocessableEntityToJSON,
} from '../models/UnprocessableEntity';
import {
    type UpgradeRequired,
    UpgradeRequiredFromJSON,
    UpgradeRequiredToJSON,
} from '../models/UpgradeRequired';

export interface GetGroupRequest {
    group_guid: string;
}

export interface GetGroupClicksRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupCodeScansByCityRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupCodeScansByCountryRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupCodeScansOverTimeRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupFeatureUsageRequest {
    group_guid: string;
    name?: Array<string>;
}

export interface GetGroupHistoricalUsageRequest {
    group_guid: string;
    name?: Array<string>;
    start_date?: string;
    end_date?: string;
    unit?: TimeUnitDWM;
}

export interface GetGroupLinkClicksByCityRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupLinkClicksByCountryRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupLinkClicksByDeviceRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupLinkClicksByReferrerRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupLinkClicksOverTimeRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupMetricsByCitiesRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupMetricsByCountriesRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupMetricsByDevicesRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupMetricsByReferrerRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupMetricsByReferringNetworksRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupMetricsOverTimeRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupPreferencesRequest {
    group_guid: string;
}

export interface GetGroupShortenCountsRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
}

export interface GetGroupTagsRequest {
    group_guid: string;
    type?: GetGroupTagsTypeEnum;
}

export interface GetGroupTopCodeScansRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    unit_reference?: string;
    decoupled?: boolean;
}

export interface GetGroupTopLinkClicksRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupTopMetricsRequest {
    group_guid: string;
    unit: TimeUnit;
    units: number;
    size?: number;
    unit_reference?: string;
}

export interface GetGroupsRequest {
    organization_guid?: string;
}

export interface PostCreateGroupExportRequest {
    group_guid: string;
    group_export_request_body: GroupExportRequestBody;
}

export interface UpdateGroupRequest {
    group_guid: string;
    group_update: GroupUpdate;
}

export interface UpdateGroupPreferencesRequest {
    group_guid: string;
    group_preferences: GroupPreferences;
}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getGroup without sending the request
     */
    async getGroupRequestOpts(requestParameters: GetGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns details for a group.
     * Retrieve a Group
     */
    async getGroupRaw(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.getGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Returns details for a group.
     * Retrieve a Group
     */
    async getGroup(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.getGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupClicks without sending the request
     */
    async getGroupClicksRequestOpts(requestParameters: GetGroupClicksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupClicks().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupClicks().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupClicks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/clicks`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get number of clicks on bitlinks in a group
     * Get clicks by group
     */
    async getGroupClicksRaw(requestParameters: GetGroupClicksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupClicks>> {
        const requestOptions = await this.getGroupClicksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupClicksFromJSON(jsonValue));
    }

    /**
     * get number of clicks on bitlinks in a group
     * Get clicks by group
     */
    async getGroupClicks(requestParameters: GetGroupClicksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupClicks> {
        const response = await this.getGroupClicksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupCodeScansByCity without sending the request
     */
    async getGroupCodeScansByCityRequestOpts(requestParameters: GetGroupCodeScansByCityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupCodeScansByCity().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupCodeScansByCity().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupCodeScansByCity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/codes/scans/cities`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get QR code scan metrics for a group broken down by city.
     * Get Scan Metrics for a Group by City
     */
    async getGroupCodeScansByCityRaw(requestParameters: GetGroupCodeScansByCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityMetrics>> {
        const requestOptions = await this.getGroupCodeScansByCityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityMetricsFromJSON(jsonValue));
    }

    /**
     * Get QR code scan metrics for a group broken down by city.
     * Get Scan Metrics for a Group by City
     */
    async getGroupCodeScansByCity(requestParameters: GetGroupCodeScansByCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityMetrics> {
        const response = await this.getGroupCodeScansByCityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupCodeScansByCountry without sending the request
     */
    async getGroupCodeScansByCountryRequestOpts(requestParameters: GetGroupCodeScansByCountryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupCodeScansByCountry().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupCodeScansByCountry().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupCodeScansByCountry().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/codes/scans/countries`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get QR code scan metrics for a group broken down by country.
     * Get Scan Metrics for a Group by Country
     */
    async getGroupCodeScansByCountryRaw(requestParameters: GetGroupCodeScansByCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupCodeScansByCountryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Get QR code scan metrics for a group broken down by country.
     * Get Scan Metrics for a Group by Country
     */
    async getGroupCodeScansByCountry(requestParameters: GetGroupCodeScansByCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupCodeScansByCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupCodeScansOverTime without sending the request
     */
    async getGroupCodeScansOverTimeRequestOpts(requestParameters: GetGroupCodeScansOverTimeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupCodeScansOverTime().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupCodeScansOverTime().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupCodeScansOverTime().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/codes/scans/over_time`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get QR code scan metrics over time for a group.
     * Get Scan Metrics for a Group Over Time
     */
    async getGroupCodeScansOverTimeRaw(requestParameters: GetGroupCodeScansOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupClicks>> {
        const requestOptions = await this.getGroupCodeScansOverTimeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupClicksFromJSON(jsonValue));
    }

    /**
     * Get QR code scan metrics over time for a group.
     * Get Scan Metrics for a Group Over Time
     */
    async getGroupCodeScansOverTime(requestParameters: GetGroupCodeScansOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupClicks> {
        const response = await this.getGroupCodeScansOverTimeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupFeatureUsage without sending the request
     */
    async getGroupFeatureUsageRequestOpts(requestParameters: GetGroupFeatureUsageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupFeatureUsage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/feature_usage`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a group\'s current feature limit usage, optionally provide limit name(s) for usage on specific limit(s)
     * Get limit usage for a group
     */
    async getGroupFeatureUsageRaw(requestParameters: GetGroupFeatureUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupFeatureUsage>> {
        const requestOptions = await this.getGroupFeatureUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFeatureUsageFromJSON(jsonValue));
    }

    /**
     * Get a group\'s current feature limit usage, optionally provide limit name(s) for usage on specific limit(s)
     * Get limit usage for a group
     */
    async getGroupFeatureUsage(requestParameters: GetGroupFeatureUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupFeatureUsage> {
        const response = await this.getGroupFeatureUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupHistoricalUsage without sending the request
     */
    async getGroupHistoricalUsageRequestOpts(requestParameters: GetGroupHistoricalUsageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupHistoricalUsage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['start_date'] != null) {
            queryParameters['start_date'] = requestParameters['start_date'];
        }

        if (requestParameters['end_date'] != null) {
            queryParameters['end_date'] = requestParameters['end_date'];
        }

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/historical_usage`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a group\'s historical usage for specific limit(s) and date range. Refer to GET /v4/groups/{group_guid}/feature_usage endpoint response for available limit names.
     * Get historical usage for a group
     */
    async getGroupHistoricalUsageRaw(requestParameters: GetGroupHistoricalUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupHistoricalUsage>> {
        const requestOptions = await this.getGroupHistoricalUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupHistoricalUsageFromJSON(jsonValue));
    }

    /**
     * Get a group\'s historical usage for specific limit(s) and date range. Refer to GET /v4/groups/{group_guid}/feature_usage endpoint response for available limit names.
     * Get historical usage for a group
     */
    async getGroupHistoricalUsage(requestParameters: GetGroupHistoricalUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupHistoricalUsage> {
        const response = await this.getGroupHistoricalUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupLinkClicksByCity without sending the request
     */
    async getGroupLinkClicksByCityRequestOpts(requestParameters: GetGroupLinkClicksByCityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupLinkClicksByCity().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupLinkClicksByCity().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupLinkClicksByCity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/cities`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get link clicks by city for all links in a group.
     * Get Group Link Clicks by City
     */
    async getGroupLinkClicksByCityRaw(requestParameters: GetGroupLinkClicksByCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityMetrics>> {
        const requestOptions = await this.getGroupLinkClicksByCityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityMetricsFromJSON(jsonValue));
    }

    /**
     * Get link clicks by city for all links in a group.
     * Get Group Link Clicks by City
     */
    async getGroupLinkClicksByCity(requestParameters: GetGroupLinkClicksByCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityMetrics> {
        const response = await this.getGroupLinkClicksByCityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupLinkClicksByCountry without sending the request
     */
    async getGroupLinkClicksByCountryRequestOpts(requestParameters: GetGroupLinkClicksByCountryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupLinkClicksByCountry().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupLinkClicksByCountry().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupLinkClicksByCountry().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/countries`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get link clicks by country for all links in a group.
     * Get Group Link Clicks by Country
     */
    async getGroupLinkClicksByCountryRaw(requestParameters: GetGroupLinkClicksByCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupLinkClicksByCountryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Get link clicks by country for all links in a group.
     * Get Group Link Clicks by Country
     */
    async getGroupLinkClicksByCountry(requestParameters: GetGroupLinkClicksByCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupLinkClicksByCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupLinkClicksByDevice without sending the request
     */
    async getGroupLinkClicksByDeviceRequestOpts(requestParameters: GetGroupLinkClicksByDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupLinkClicksByDevice().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupLinkClicksByDevice().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupLinkClicksByDevice().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/devices`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get link clicks by device for all links in a group.
     * Get Group Link Clicks by Device
     */
    async getGroupLinkClicksByDeviceRaw(requestParameters: GetGroupLinkClicksByDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGroupLinkClicksByDevice200Response>> {
        const requestOptions = await this.getGroupLinkClicksByDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGroupLinkClicksByDevice200ResponseFromJSON(jsonValue));
    }

    /**
     * Get link clicks by device for all links in a group.
     * Get Group Link Clicks by Device
     */
    async getGroupLinkClicksByDevice(requestParameters: GetGroupLinkClicksByDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGroupLinkClicksByDevice200Response> {
        const response = await this.getGroupLinkClicksByDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupLinkClicksByReferrer without sending the request
     */
    async getGroupLinkClicksByReferrerRequestOpts(requestParameters: GetGroupLinkClicksByReferrerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupLinkClicksByReferrer().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupLinkClicksByReferrer().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupLinkClicksByReferrer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/referrers`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get link clicks by referrer for all links in a group.
     * Get Group Link Clicks by Referrer
     */
    async getGroupLinkClicksByReferrerRaw(requestParameters: GetGroupLinkClicksByReferrerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupLinkClicksByReferrerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Get link clicks by referrer for all links in a group.
     * Get Group Link Clicks by Referrer
     */
    async getGroupLinkClicksByReferrer(requestParameters: GetGroupLinkClicksByReferrerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupLinkClicksByReferrerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupLinkClicksOverTime without sending the request
     */
    async getGroupLinkClicksOverTimeRequestOpts(requestParameters: GetGroupLinkClicksOverTimeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupLinkClicksOverTime().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupLinkClicksOverTime().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupLinkClicksOverTime().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/over_time`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get link clicks over time for all links in a group.
     * Get Group Link Clicks Over Time
     */
    async getGroupLinkClicksOverTimeRaw(requestParameters: GetGroupLinkClicksOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupClicks>> {
        const requestOptions = await this.getGroupLinkClicksOverTimeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupClicksFromJSON(jsonValue));
    }

    /**
     * Get link clicks over time for all links in a group.
     * Get Group Link Clicks Over Time
     */
    async getGroupLinkClicksOverTime(requestParameters: GetGroupLinkClicksOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupClicks> {
        const response = await this.getGroupLinkClicksOverTimeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsByCities without sending the request
     */
    async getGroupMetricsByCitiesRequestOpts(requestParameters: GetGroupMetricsByCitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsByCities().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsByCities().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsByCities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/cities`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the geographic origins of click traffic by city for the specified group.
     * Get Click Metrics for a Group by City
     */
    async getGroupMetricsByCitiesRaw(requestParameters: GetGroupMetricsByCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CityMetrics>> {
        const requestOptions = await this.getGroupMetricsByCitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CityMetricsFromJSON(jsonValue));
    }

    /**
     * Returns the geographic origins of click traffic by city for the specified group.
     * Get Click Metrics for a Group by City
     */
    async getGroupMetricsByCities(requestParameters: GetGroupMetricsByCitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CityMetrics> {
        const response = await this.getGroupMetricsByCitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsByCountries without sending the request
     */
    async getGroupMetricsByCountriesRequestOpts(requestParameters: GetGroupMetricsByCountriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsByCountries().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsByCountries().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsByCountries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/countries`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the geographic origins of click traffic by country for the specified group.
     * Get Click Metrics for a Group by Country
     */
    async getGroupMetricsByCountriesRaw(requestParameters: GetGroupMetricsByCountriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupMetricsByCountriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Returns the geographic origins of click traffic by country for the specified group.
     * Get Click Metrics for a Group by Country
     */
    async getGroupMetricsByCountries(requestParameters: GetGroupMetricsByCountriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupMetricsByCountriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsByDevices without sending the request
     */
    async getGroupMetricsByDevicesRequestOpts(requestParameters: GetGroupMetricsByDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsByDevices().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsByDevices().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsByDevices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/devices`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the device types generating click traffic to the specified group\'s links.
     * Get Click Metrics for a Group by Device Type
     */
    async getGroupMetricsByDevicesRaw(requestParameters: GetGroupMetricsByDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceMetrics>> {
        const requestOptions = await this.getGroupMetricsByDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceMetricsFromJSON(jsonValue));
    }

    /**
     * Returns the device types generating click traffic to the specified group\'s links.
     * Get Click Metrics for a Group by Device Type
     */
    async getGroupMetricsByDevices(requestParameters: GetGroupMetricsByDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceMetrics> {
        const response = await this.getGroupMetricsByDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsByReferrer without sending the request
     */
    async getGroupMetricsByReferrerRequestOpts(requestParameters: GetGroupMetricsByReferrerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsByReferrer().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsByReferrer().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsByReferrer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/referrers`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns metrics by referrer for the specified group\'s links.
     * Get Click Metrics for a Group by Referrer
     */
    async getGroupMetricsByReferrerRaw(requestParameters: GetGroupMetricsByReferrerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupMetricsByReferrerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Returns metrics by referrer for the specified group\'s links.
     * Get Click Metrics for a Group by Referrer
     */
    async getGroupMetricsByReferrer(requestParameters: GetGroupMetricsByReferrerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupMetricsByReferrerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsByReferringNetworks without sending the request
     */
    async getGroupMetricsByReferringNetworksRequestOpts(requestParameters: GetGroupMetricsByReferringNetworksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsByReferringNetworks().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsByReferringNetworks().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsByReferringNetworks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/referring_networks`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns metrics by referring networks for the specified group\'s links.
     * Get Click Metrics for a Group by Referring Networks
     */
    async getGroupMetricsByReferringNetworksRaw(requestParameters: GetGroupMetricsByReferringNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClickMetrics>> {
        const requestOptions = await this.getGroupMetricsByReferringNetworksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClickMetricsFromJSON(jsonValue));
    }

    /**
     * Returns metrics by referring networks for the specified group\'s links.
     * Get Click Metrics for a Group by Referring Networks
     */
    async getGroupMetricsByReferringNetworks(requestParameters: GetGroupMetricsByReferringNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClickMetrics> {
        const response = await this.getGroupMetricsByReferringNetworksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupMetricsOverTime without sending the request
     */
    async getGroupMetricsOverTimeRequestOpts(requestParameters: GetGroupMetricsOverTimeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupMetricsOverTime().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupMetricsOverTime().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupMetricsOverTime().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/engagements/over_time`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get group engagement metrics over time for all links in a group.
     * Get Group Metrics Over Time
     */
    async getGroupMetricsOverTimeRaw(requestParameters: GetGroupMetricsOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupClicks>> {
        const requestOptions = await this.getGroupMetricsOverTimeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupClicksFromJSON(jsonValue));
    }

    /**
     * Get group engagement metrics over time for all links in a group.
     * Get Group Metrics Over Time
     */
    async getGroupMetricsOverTime(requestParameters: GetGroupMetricsOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupClicks> {
        const response = await this.getGroupMetricsOverTimeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupPreferences without sending the request
     */
    async getGroupPreferencesRequestOpts(requestParameters: GetGroupPreferencesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupPreferences().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/preferences`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns preferences for the specified group.
     * Retrieve Group Preferences
     */
    async getGroupPreferencesRaw(requestParameters: GetGroupPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupPreferences>> {
        const requestOptions = await this.getGroupPreferencesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupPreferencesFromJSON(jsonValue));
    }

    /**
     * Returns preferences for the specified group.
     * Retrieve Group Preferences
     */
    async getGroupPreferences(requestParameters: GetGroupPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupPreferences> {
        const response = await this.getGroupPreferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupShortenCounts without sending the request
     */
    async getGroupShortenCountsRequestOpts(requestParameters: GetGroupShortenCountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupShortenCounts().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupShortenCounts().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupShortenCounts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/shorten_counts`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all the shorten counts for a group.
     * Retrieve Group Shorten Counts
     */
    async getGroupShortenCountsRaw(requestParameters: GetGroupShortenCountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metrics>> {
        const requestOptions = await this.getGroupShortenCountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricsFromJSON(jsonValue));
    }

    /**
     * Returns all the shorten counts for a group.
     * Retrieve Group Shorten Counts
     */
    async getGroupShortenCounts(requestParameters: GetGroupShortenCountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metrics> {
        const response = await this.getGroupShortenCountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupTags without sending the request
     */
    async getGroupTagsRequestOpts(requestParameters: GetGroupTagsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupTags().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/tags`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the tags currently used in the specified group. Maximum 1000.
     * Retrieve Tags by Group
     */
    async getGroupTagsRaw(requestParameters: GetGroupTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tags>> {
        const requestOptions = await this.getGroupTagsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagsFromJSON(jsonValue));
    }

    /**
     * Returns the tags currently used in the specified group. Maximum 1000.
     * Retrieve Tags by Group
     */
    async getGroupTags(requestParameters: GetGroupTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tags> {
        const response = await this.getGroupTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupTopCodeScans without sending the request
     */
    async getGroupTopCodeScansRequestOpts(requestParameters: GetGroupTopCodeScansRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupTopCodeScans().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupTopCodeScans().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupTopCodeScans().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        if (requestParameters['decoupled'] != null) {
            queryParameters['decoupled'] = requestParameters['decoupled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/codes/scans/top`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get top performing QR codes by scan count for all codes in a group.
     * Get Top Performing QR Codes for a Group
     */
    async getGroupTopCodeScansRaw(requestParameters: GetGroupTopCodeScansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGroupTopCodeScans200Response>> {
        const requestOptions = await this.getGroupTopCodeScansRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGroupTopCodeScans200ResponseFromJSON(jsonValue));
    }

    /**
     * Get top performing QR codes by scan count for all codes in a group.
     * Get Top Performing QR Codes for a Group
     */
    async getGroupTopCodeScans(requestParameters: GetGroupTopCodeScansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGroupTopCodeScans200Response> {
        const response = await this.getGroupTopCodeScansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupTopLinkClicks without sending the request
     */
    async getGroupTopLinkClicksRequestOpts(requestParameters: GetGroupTopLinkClicksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupTopLinkClicks().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupTopLinkClicks().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupTopLinkClicks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/links/clicks/top`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get top performing links by click for all links in a group.
     * Get Group Top Performing Links by Click
     */
    async getGroupTopLinkClicksRaw(requestParameters: GetGroupTopLinkClicksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SortedLinks>> {
        const requestOptions = await this.getGroupTopLinkClicksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SortedLinksFromJSON(jsonValue));
    }

    /**
     * Get top performing links by click for all links in a group.
     * Get Group Top Performing Links by Click
     */
    async getGroupTopLinkClicks(requestParameters: GetGroupTopLinkClicksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SortedLinks> {
        const response = await this.getGroupTopLinkClicksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupTopMetrics without sending the request
     */
    async getGroupTopMetricsRequestOpts(requestParameters: GetGroupTopMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling getGroupTopMetrics().'
            );
        }

        if (requestParameters['unit'] == null) {
            throw new runtime.RequiredError(
                'unit',
                'Required parameter "unit" was null or undefined when calling getGroupTopMetrics().'
            );
        }

        if (requestParameters['units'] == null) {
            throw new runtime.RequiredError(
                'units',
                'Required parameter "units" was null or undefined when calling getGroupTopMetrics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['units'] != null) {
            queryParameters['units'] = requestParameters['units'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit_reference'] != null) {
            queryParameters['unit_reference'] = requestParameters['unit_reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/engagements/top`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get top performing links by engagement for all links in a group.
     * Get Group Top Performing Links by Engagement
     */
    async getGroupTopMetricsRaw(requestParameters: GetGroupTopMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SortedLinks>> {
        const requestOptions = await this.getGroupTopMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SortedLinksFromJSON(jsonValue));
    }

    /**
     * Get top performing links by engagement for all links in a group.
     * Get Group Top Performing Links by Engagement
     */
    async getGroupTopMetrics(requestParameters: GetGroupTopMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SortedLinks> {
        const response = await this.getGroupTopMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroups without sending the request
     */
    async getGroupsRequestOpts(requestParameters: GetGroupsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['organization_guid'] != null) {
            queryParameters['organization_guid'] = requestParameters['organization_guid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of groups in the organization.
     * Retrieve Groups
     */
    async getGroupsRaw(requestParameters: GetGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Groups>> {
        const requestOptions = await this.getGroupsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupsFromJSON(jsonValue));
    }

    /**
     * Returns a list of groups in the organization.
     * Retrieve Groups
     */
    async getGroups(requestParameters: GetGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Groups> {
        const response = await this.getGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCreateGroupExport without sending the request
     */
    async postCreateGroupExportRequestOpts(requestParameters: PostCreateGroupExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling postCreateGroupExport().'
            );
        }

        if (requestParameters['group_export_request_body'] == null) {
            throw new runtime.RequiredError(
                'group_export_request_body',
                'Required parameter "group_export_request_body" was null or undefined when calling postCreateGroupExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/exports`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupExportRequestBodyToJSON(requestParameters['group_export_request_body']),
        };
    }

    /**
     * Build a CSV export synchronously and return it inline as a base64 data URI plus metadata. The export_type field selects the CSV shape: link_engagements_batch (engagement metrics for explicit bitlinks or a filter), links_list (link metadata roster), or qr_codes_list (QR code metadata roster). Row caps apply per request: 200 rows when metrics are included (link_engagements_batch, or include_metrics on a list export); 1000 rows for metadata-only list exports. When the match set exceeds the cap, truncated is true and only the first cap rows are returned; row_count reports how many data rows are in the CSV. 
     * Create an inline CSV export for a group
     */
    async postCreateGroupExportRaw(requestParameters: PostCreateGroupExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupExportResponse>> {
        const requestOptions = await this.postCreateGroupExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupExportResponseFromJSON(jsonValue));
    }

    /**
     * Build a CSV export synchronously and return it inline as a base64 data URI plus metadata. The export_type field selects the CSV shape: link_engagements_batch (engagement metrics for explicit bitlinks or a filter), links_list (link metadata roster), or qr_codes_list (QR code metadata roster). Row caps apply per request: 200 rows when metrics are included (link_engagements_batch, or include_metrics on a list export); 1000 rows for metadata-only list exports. When the match set exceeds the cap, truncated is true and only the first cap rows are returned; row_count reports how many data rows are in the CSV. 
     * Create an inline CSV export for a group
     */
    async postCreateGroupExport(requestParameters: PostCreateGroupExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupExportResponse> {
        const response = await this.postCreateGroupExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGroup without sending the request
     */
    async updateGroupRequestOpts(requestParameters: UpdateGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling updateGroup().'
            );
        }

        if (requestParameters['group_update'] == null) {
            throw new runtime.RequiredError(
                'group_update',
                'Required parameter "group_update" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GroupUpdateToJSON(requestParameters['group_update']),
        };
    }

    /**
     * Updates the details of a group.
     * Update a Group
     */
    async updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.updateGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Updates the details of a group.
     * Update a Group
     */
    async updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGroupPreferences without sending the request
     */
    async updateGroupPreferencesRequestOpts(requestParameters: UpdateGroupPreferencesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['group_guid'] == null) {
            throw new runtime.RequiredError(
                'group_guid',
                'Required parameter "group_guid" was null or undefined when calling updateGroupPreferences().'
            );
        }

        if (requestParameters['group_preferences'] == null) {
            throw new runtime.RequiredError(
                'group_preferences',
                'Required parameter "group_preferences" was null or undefined when calling updateGroupPreferences().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/{group_guid}/preferences`;
        urlPath = urlPath.replace('{group_guid}', encodeURIComponent(String(requestParameters['group_guid'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GroupPreferencesToJSON(requestParameters['group_preferences']),
        };
    }

    /**
     * Updates preferences for a group.
     * Update Group Preferences
     */
    async updateGroupPreferencesRaw(requestParameters: UpdateGroupPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupPreferences>> {
        const requestOptions = await this.updateGroupPreferencesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupPreferencesFromJSON(jsonValue));
    }

    /**
     * Updates preferences for a group.
     * Update Group Preferences
     */
    async updateGroupPreferences(requestParameters: UpdateGroupPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupPreferences> {
        const response = await this.updateGroupPreferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum GetGroupTagsTypeEnum {
    bitlink = 'bitlink',
    qr_code = 'qr_code'
}
