/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityLog
 */
export interface ActivityLog {
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    action_description?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    action_login?: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof ActivityLog
     */
    ts?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    org_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    country_code?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    sub_region?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLog
     */
    isp?: string;
    /**
     * Indicates an action take by Bitly
     * @type {boolean}
     * @memberof ActivityLog
     */
    bitly_admin?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ActivityLog
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ActivityLog interface.
 */
export function instanceOfActivityLog(value: object): value is ActivityLog {
    return true;
}

export function ActivityLogFromJSON(json: any): ActivityLog {
    return ActivityLogFromJSONTyped(json, false);
}

export function ActivityLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLog {
    if (json == null) {
        return json;
    }
    return {
        
        'action_description': json['action_description'] == null ? undefined : json['action_description'],
        'action_login': json['action_login'] == null ? undefined : json['action_login'],
        'ts': json['ts'] == null ? undefined : json['ts'],
        'user': json['user'] == null ? undefined : json['user'],
        'action': json['action'] == null ? undefined : json['action'],
        'org_guid': json['org_guid'] == null ? undefined : json['org_guid'],
        'id': json['id'] == null ? undefined : json['id'],
        'country_code': json['country_code'] == null ? undefined : json['country_code'],
        'region': json['region'] == null ? undefined : json['region'],
        'sub_region': json['sub_region'] == null ? undefined : json['sub_region'],
        'city': json['city'] == null ? undefined : json['city'],
        'isp': json['isp'] == null ? undefined : json['isp'],
        'bitly_admin': json['bitly_admin'] == null ? undefined : json['bitly_admin'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ActivityLogToJSON(json: any): ActivityLog {
    return ActivityLogToJSONTyped(json, false);
}

export function ActivityLogToJSONTyped(value?: ActivityLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_description': value['action_description'],
        'action_login': value['action_login'],
        'ts': value['ts'],
        'user': value['user'],
        'action': value['action'],
        'org_guid': value['org_guid'],
        'id': value['id'],
        'country_code': value['country_code'],
        'region': value['region'],
        'sub_region': value['sub_region'],
        'city': value['city'],
        'isp': value['isp'],
        'bitly_admin': value['bitly_admin'],
        'metadata': value['metadata'],
    };
}

