/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityLog } from './ActivityLog';
import {
    ActivityLogFromJSON,
    ActivityLogFromJSONTyped,
    ActivityLogToJSON,
    ActivityLogToJSONTyped,
} from './ActivityLog';

/**
 * 
 * @export
 * @interface ActivityLogs
 */
export interface ActivityLogs {
    /**
     * 
     * @type {string}
     * @memberof ActivityLogs
     */
    next_page?: string;
    /**
     * 
     * @type {Array<ActivityLog>}
     * @memberof ActivityLogs
     */
    activity?: Array<ActivityLog>;
}

/**
 * Check if a given object implements the ActivityLogs interface.
 */
export function instanceOfActivityLogs(value: object): value is ActivityLogs {
    return true;
}

export function ActivityLogsFromJSON(json: any): ActivityLogs {
    return ActivityLogsFromJSONTyped(json, false);
}

export function ActivityLogsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogs {
    if (json == null) {
        return json;
    }
    return {
        
        'next_page': json['next_page'] == null ? undefined : json['next_page'],
        'activity': json['activity'] == null ? undefined : ((json['activity'] as Array<any>).map(ActivityLogFromJSON)),
    };
}

export function ActivityLogsToJSON(json: any): ActivityLogs {
    return ActivityLogsToJSONTyped(json, false);
}

export function ActivityLogsToJSONTyped(value?: ActivityLogs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_page': value['next_page'],
        'activity': value['activity'] == null ? undefined : ((value['activity'] as Array<any>).map(ActivityLogToJSON)),
    };
}

