/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddChannelBitlinksResponse
 */
export interface AddChannelBitlinksResponse {
    /**
     * The GUID of the channel the bitlinks were added to.
     * @type {string}
     * @memberof AddChannelBitlinksResponse
     */
    channel_guid?: string;
    /**
     * The GUID of the campaign the bitlinks are associated with on this channel.
     * @type {string}
     * @memberof AddChannelBitlinksResponse
     */
    campaign_guid?: string;
    /**
     * Bitlink IDs now associated with the channel.
     * @type {Array<string>}
     * @memberof AddChannelBitlinksResponse
     */
    bitlinks?: Array<string>;
}

/**
 * Check if a given object implements the AddChannelBitlinksResponse interface.
 */
export function instanceOfAddChannelBitlinksResponse(value: object): value is AddChannelBitlinksResponse {
    return true;
}

export function AddChannelBitlinksResponseFromJSON(json: any): AddChannelBitlinksResponse {
    return AddChannelBitlinksResponseFromJSONTyped(json, false);
}

export function AddChannelBitlinksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddChannelBitlinksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'channel_guid': json['channel_guid'] == null ? undefined : json['channel_guid'],
        'campaign_guid': json['campaign_guid'] == null ? undefined : json['campaign_guid'],
        'bitlinks': json['bitlinks'] == null ? undefined : json['bitlinks'],
    };
}

export function AddChannelBitlinksResponseToJSON(json: any): AddChannelBitlinksResponse {
    return AddChannelBitlinksResponseToJSONTyped(json, false);
}

export function AddChannelBitlinksResponseToJSONTyped(value?: AddChannelBitlinksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_guid': value['channel_guid'],
        'campaign_guid': value['campaign_guid'],
        'bitlinks': value['bitlinks'],
    };
}

