/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddChannelBitlinksRequest
 */
export interface AddChannelBitlinksRequest {
    /**
     * The campaign to associate the given bitlinks with on this channel. All bitlinks in the request are associated with this single campaign_guid.
     * @type {string}
     * @memberof AddChannelBitlinksRequest
     */
    campaign_guid: string;
    /**
     * Bitlink IDs to add to the channel, up to 100 per request. Bitlinks already associated with the channel are left untouched.
     * @type {Array<string>}
     * @memberof AddChannelBitlinksRequest
     */
    bitlinks: Array<string>;
}

/**
 * Check if a given object implements the AddChannelBitlinksRequest interface.
 */
export function instanceOfAddChannelBitlinksRequest(value: object): value is AddChannelBitlinksRequest {
    if (!('campaign_guid' in value) || value['campaign_guid'] === undefined) return false;
    if (!('bitlinks' in value) || value['bitlinks'] === undefined) return false;
    return true;
}

export function AddChannelBitlinksRequestFromJSON(json: any): AddChannelBitlinksRequest {
    return AddChannelBitlinksRequestFromJSONTyped(json, false);
}

export function AddChannelBitlinksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddChannelBitlinksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign_guid': json['campaign_guid'],
        'bitlinks': json['bitlinks'],
    };
}

export function AddChannelBitlinksRequestToJSON(json: any): AddChannelBitlinksRequest {
    return AddChannelBitlinksRequestToJSONTyped(json, false);
}

export function AddChannelBitlinksRequestToJSONTyped(value?: AddChannelBitlinksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_guid': value['campaign_guid'],
        'bitlinks': value['bitlinks'],
    };
}

