/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsReportContent
 */
export interface AnalyticsReportContent {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsReportContent
     */
    title?: string;
}

/**
 * Check if a given object implements the AnalyticsReportContent interface.
 */
export function instanceOfAnalyticsReportContent(value: object): value is AnalyticsReportContent {
    return true;
}

export function AnalyticsReportContentFromJSON(json: any): AnalyticsReportContent {
    return AnalyticsReportContentFromJSONTyped(json, false);
}

export function AnalyticsReportContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsReportContent {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AnalyticsReportContentToJSON(json: any): AnalyticsReportContent {
    return AnalyticsReportContentToJSONTyped(json, false);
}

export function AnalyticsReportContentToJSONTyped(value?: AnalyticsReportContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

