/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnualRenewalReminderRequest
 */
export interface AnnualRenewalReminderRequest {
    /**
     * 
     * @type {string}
     * @memberof AnnualRenewalReminderRequest
     */
    subscription_id?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnualRenewalReminderRequest
     */
    org_guid?: string;
}

/**
 * Check if a given object implements the AnnualRenewalReminderRequest interface.
 */
export function instanceOfAnnualRenewalReminderRequest(value: object): value is AnnualRenewalReminderRequest {
    return true;
}

export function AnnualRenewalReminderRequestFromJSON(json: any): AnnualRenewalReminderRequest {
    return AnnualRenewalReminderRequestFromJSONTyped(json, false);
}

export function AnnualRenewalReminderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnualRenewalReminderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_id': json['subscription_ID'] == null ? undefined : json['subscription_ID'],
        'org_guid': json['org_guid'] == null ? undefined : json['org_guid'],
    };
}

export function AnnualRenewalReminderRequestToJSON(json: any): AnnualRenewalReminderRequest {
    return AnnualRenewalReminderRequestToJSONTyped(json, false);
}

export function AnnualRenewalReminderRequestToJSONTyped(value?: AnnualRenewalReminderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_ID': value['subscription_id'],
        'org_guid': value['org_guid'],
    };
}

