/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyDiscount
 */
export interface ApplyDiscount {
    /**
     * 
     * @type {string}
     * @memberof ApplyDiscount
     */
    promo_code?: string;
}

/**
 * Check if a given object implements the ApplyDiscount interface.
 */
export function instanceOfApplyDiscount(value: object): value is ApplyDiscount {
    return true;
}

export function ApplyDiscountFromJSON(json: any): ApplyDiscount {
    return ApplyDiscountFromJSONTyped(json, false);
}

export function ApplyDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyDiscount {
    if (json == null) {
        return json;
    }
    return {
        
        'promo_code': json['promo_code'] == null ? undefined : json['promo_code'],
    };
}

export function ApplyDiscountToJSON(json: any): ApplyDiscount {
    return ApplyDiscountToJSONTyped(json, false);
}

export function ApplyDiscountToJSONTyped(value?: ApplyDiscount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promo_code': value['promo_code'],
    };
}

