/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldError } from './FieldError';
import {
    FieldErrorFromJSON,
    FieldErrorFromJSONTyped,
    FieldErrorToJSON,
    FieldErrorToJSONTyped,
} from './FieldError';

/**
 * BAD_REQUEST
 * @export
 * @interface BadRequest
 */
export interface BadRequest {
    /**
     * 
     * @type {string}
     * @memberof BadRequest
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof BadRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BadRequest
     */
    resource?: string;
    /**
     * 
     * @type {Array<FieldError>}
     * @memberof BadRequest
     */
    errors?: Array<FieldError>;
}

/**
 * Check if a given object implements the BadRequest interface.
 */
export function instanceOfBadRequest(value: object): value is BadRequest {
    return true;
}

export function BadRequestFromJSON(json: any): BadRequest {
    return BadRequestFromJSONTyped(json, false);
}

export function BadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'description': json['description'] == null ? undefined : json['description'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(FieldErrorFromJSON)),
    };
}

export function BadRequestToJSON(json: any): BadRequest {
    return BadRequestToJSONTyped(json, false);
}

export function BadRequestToJSONTyped(value?: BadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'description': value['description'],
        'resource': value['resource'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(FieldErrorToJSON)),
    };
}

