/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BitlySiteContent
 */
export interface BitlySiteContent {
    /**
     * 
     * @type {string}
     * @memberof BitlySiteContent
     */
    display_name?: string;
    /**
     * 
     * @type {string}
     * @memberof BitlySiteContent
     */
    description?: string;
}

/**
 * Check if a given object implements the BitlySiteContent interface.
 */
export function instanceOfBitlySiteContent(value: object): value is BitlySiteContent {
    return true;
}

export function BitlySiteContentFromJSON(json: any): BitlySiteContent {
    return BitlySiteContentFromJSONTyped(json, false);
}

export function BitlySiteContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitlySiteContent {
    if (json == null) {
        return json;
    }
    return {
        
        'display_name': json['display_name'] == null ? undefined : json['display_name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function BitlySiteContentToJSON(json: any): BitlySiteContent {
    return BitlySiteContentToJSONTyped(json, false);
}

export function BitlySiteContentToJSONTyped(value?: BitlySiteContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['display_name'],
        'description': value['description'],
    };
}

