/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QRScans } from './QRScans';
import {
    QRScansFromJSON,
    QRScansFromJSONTyped,
    QRScansToJSON,
    QRScansToJSONTyped,
} from './QRScans';

/**
 * 
 * @export
 * @interface BitlinkScans
 */
export interface BitlinkScans {
    /**
     * 
     * @type {Array<QRScans>}
     * @memberof BitlinkScans
     */
    scans?: Array<QRScans>;
    /**
     * 
     * @type {number}
     * @memberof BitlinkScans
     */
    units?: number;
    /**
     * 
     * @type {string}
     * @memberof BitlinkScans
     */
    unit?: BitlinkScansUnitEnum;
    /**
     * 
     * @type {string}
     * @memberof BitlinkScans
     */
    unit_reference?: string;
}

/**
* @export
* @enum {string}
*/
export enum BitlinkScansUnitEnum {
    minute = 'minute',
    hour = 'hour',
    day = 'day',
    week = 'week',
    month = 'month'
}


/**
 * Check if a given object implements the BitlinkScans interface.
 */
export function instanceOfBitlinkScans(value: object): value is BitlinkScans {
    return true;
}

export function BitlinkScansFromJSON(json: any): BitlinkScans {
    return BitlinkScansFromJSONTyped(json, false);
}

export function BitlinkScansFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitlinkScans {
    if (json == null) {
        return json;
    }
    return {
        
        'scans': json['scans'] == null ? undefined : ((json['scans'] as Array<any>).map(QRScansFromJSON)),
        'units': json['units'] == null ? undefined : json['units'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'unit_reference': json['unit_reference'] == null ? undefined : json['unit_reference'],
    };
}

export function BitlinkScansToJSON(json: any): BitlinkScans {
    return BitlinkScansToJSONTyped(json, false);
}

export function BitlinkScansToJSONTyped(value?: BitlinkScans | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scans': value['scans'] == null ? undefined : ((value['scans'] as Array<any>).map(QRScansToJSON)),
        'units': value['units'],
        'unit': value['unit'],
        'unit_reference': value['unit_reference'],
    };
}

