/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BitlinkContent
 */
export interface BitlinkContent {
    /**
     * The bitlink ID (domain/hash) of the short link displayed on this block
     * @type {string}
     * @memberof BitlinkContent
     */
    bitlink_id?: string;
    /**
     * Display title of the bitlink block, up to 255 characters
     * @type {string}
     * @memberof BitlinkContent
     */
    link_title?: string;
    /**
     * Optional subtitle shown on the bitlink block, up to 255 characters
     * @type {string}
     * @memberof BitlinkContent
     */
    description?: string;
    /**
     * Whether this bitlink block is pinned to the top of the site
     * @type {boolean}
     * @memberof BitlinkContent
     */
    is_pinned?: boolean;
    /**
     * Public URL of the thumbnail image shown on this bitlink block
     * @type {string}
     * @memberof BitlinkContent
     */
    image_url?: string;
    /**
     * GUID of the uploaded thumbnail image for this bitlink block
     * @type {string}
     * @memberof BitlinkContent
     */
    image_guid?: string;
    /**
     * JSON-encoded crop rectangle for the thumbnail image, with Min and Max coordinates in the range 0-1
     * @type {string}
     * @memberof BitlinkContent
     */
    crop?: string;
}

/**
 * Check if a given object implements the BitlinkContent interface.
 */
export function instanceOfBitlinkContent(value: object): value is BitlinkContent {
    return true;
}

export function BitlinkContentFromJSON(json: any): BitlinkContent {
    return BitlinkContentFromJSONTyped(json, false);
}

export function BitlinkContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitlinkContent {
    if (json == null) {
        return json;
    }
    return {
        
        'bitlink_id': json['bitlink_id'] == null ? undefined : json['bitlink_id'],
        'link_title': json['link_title'] == null ? undefined : json['link_title'],
        'description': json['description'] == null ? undefined : json['description'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'image_url': json['image_url'] == null ? undefined : json['image_url'],
        'image_guid': json['image_guid'] == null ? undefined : json['image_guid'],
        'crop': json['crop'] == null ? undefined : json['crop'],
    };
}

export function BitlinkContentToJSON(json: any): BitlinkContent {
    return BitlinkContentToJSONTyped(json, false);
}

export function BitlinkContentToJSONTyped(value?: BitlinkContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bitlink_id': value['bitlink_id'],
        'link_title': value['link_title'],
        'description': value['description'],
        'is_pinned': value['is_pinned'],
        'image_url': value['image_url'],
        'image_guid': value['image_guid'],
        'crop': value['crop'],
    };
}

