/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockOrder } from './BlockOrder';
import {
    BlockOrderFromJSON,
    BlockOrderFromJSONTyped,
    BlockOrderToJSON,
    BlockOrderToJSONTyped,
} from './BlockOrder';

/**
 * 
 * @export
 * @interface BlockOrders
 */
export interface BlockOrders {
    /**
     * 
     * @type {Array<BlockOrder>}
     * @memberof BlockOrders
     */
    block_order?: Array<BlockOrder>;
}

/**
 * Check if a given object implements the BlockOrders interface.
 */
export function instanceOfBlockOrders(value: object): value is BlockOrders {
    return true;
}

export function BlockOrdersFromJSON(json: any): BlockOrders {
    return BlockOrdersFromJSONTyped(json, false);
}

export function BlockOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'block_order': json['block_order'] == null ? undefined : ((json['block_order'] as Array<any>).map(BlockOrderFromJSON)),
    };
}

export function BlockOrdersToJSON(json: any): BlockOrders {
    return BlockOrdersToJSONTyped(json, false);
}

export function BlockOrdersToJSONTyped(value?: BlockOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'block_order': value['block_order'] == null ? undefined : ((value['block_order'] as Array<any>).map(BlockOrderToJSON)),
    };
}

