/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockOrder
 */
export interface BlockOrder {
    /**
     * 
     * @type {string}
     * @memberof BlockOrder
     */
    block_id?: string;
    /**
     * 
     * @type {number}
     * @memberof BlockOrder
     */
    sort_order?: number;
}

/**
 * Check if a given object implements the BlockOrder interface.
 */
export function instanceOfBlockOrder(value: object): value is BlockOrder {
    return true;
}

export function BlockOrderFromJSON(json: any): BlockOrder {
    return BlockOrderFromJSONTyped(json, false);
}

export function BlockOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'block_id': json['block_id'] == null ? undefined : json['block_id'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function BlockOrderToJSON(json: any): BlockOrder {
    return BlockOrderToJSONTyped(json, false);
}

export function BlockOrderToJSONTyped(value?: BlockOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'block_id': value['block_id'],
        'sort_order': value['sort_order'],
    };
}

