/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkUpload } from './BulkUpload';
import {
    BulkUploadFromJSON,
    BulkUploadFromJSONTyped,
    BulkUploadToJSON,
    BulkUploadToJSONTyped,
} from './BulkUpload';

/**
 * 
 * @export
 * @interface BulkUploads
 */
export interface BulkUploads {
    /**
     * 
     * @type {Array<BulkUpload>}
     * @memberof BulkUploads
     */
    uploads: Array<BulkUpload>;
}

/**
 * Check if a given object implements the BulkUploads interface.
 */
export function instanceOfBulkUploads(value: object): value is BulkUploads {
    if (!('uploads' in value) || value['uploads'] === undefined) return false;
    return true;
}

export function BulkUploadsFromJSON(json: any): BulkUploads {
    return BulkUploadsFromJSONTyped(json, false);
}

export function BulkUploadsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUploads {
    if (json == null) {
        return json;
    }
    return {
        
        'uploads': ((json['uploads'] as Array<any>).map(BulkUploadFromJSON)),
    };
}

export function BulkUploadsToJSON(json: any): BulkUploads {
    return BulkUploadsToJSONTyped(json, false);
}

export function BulkUploadsToJSONTyped(value?: BulkUploads | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploads': ((value['uploads'] as Array<any>).map(BulkUploadToJSON)),
    };
}

