/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignModify
 */
export interface CampaignModify {
    /**
     * 
     * @type {string}
     * @memberof CampaignModify
     */
    group_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignModify
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignModify
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CampaignModify
     */
    channel_guids?: Array<string>;
}

/**
 * Check if a given object implements the CampaignModify interface.
 */
export function instanceOfCampaignModify(value: object): value is CampaignModify {
    return true;
}

export function CampaignModifyFromJSON(json: any): CampaignModify {
    return CampaignModifyFromJSONTyped(json, false);
}

export function CampaignModifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignModify {
    if (json == null) {
        return json;
    }
    return {
        
        'group_guid': json['group_guid'] == null ? undefined : json['group_guid'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'channel_guids': json['channel_guids'] == null ? undefined : json['channel_guids'],
    };
}

export function CampaignModifyToJSON(json: any): CampaignModify {
    return CampaignModifyToJSONTyped(json, false);
}

export function CampaignModifyToJSONTyped(value?: CampaignModify | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_guid': value['group_guid'],
        'name': value['name'],
        'description': value['description'],
        'channel_guids': value['channel_guids'],
    };
}

