/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelBitlinks } from './ChannelBitlinks';
import {
    ChannelBitlinksFromJSON,
    ChannelBitlinksFromJSONTyped,
    ChannelBitlinksToJSON,
    ChannelBitlinksToJSONTyped,
} from './ChannelBitlinks';

/**
 * 
 * @export
 * @interface CampaignChannel
 */
export interface CampaignChannel {
    /**
     * 
     * @type {string}
     * @memberof CampaignChannel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignChannel
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignChannel
     */
    campaign_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignChannel
     */
    channel_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignChannel
     */
    channel_name?: string;
    /**
     * 
     * @type {ChannelBitlinks}
     * @memberof CampaignChannel
     */
    channel_bitlinks?: ChannelBitlinks;
}

/**
 * Check if a given object implements the CampaignChannel interface.
 */
export function instanceOfCampaignChannel(value: object): value is CampaignChannel {
    return true;
}

export function CampaignChannelFromJSON(json: any): CampaignChannel {
    return CampaignChannelFromJSONTyped(json, false);
}

export function CampaignChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignChannel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'campaign_guid': json['campaign_guid'] == null ? undefined : json['campaign_guid'],
        'channel_guid': json['channel_guid'] == null ? undefined : json['channel_guid'],
        'channel_name': json['channel_name'] == null ? undefined : json['channel_name'],
        'channel_bitlinks': json['channel_bitlinks'] == null ? undefined : ChannelBitlinksFromJSON(json['channel_bitlinks']),
    };
}

export function CampaignChannelToJSON(json: any): CampaignChannel {
    return CampaignChannelToJSONTyped(json, false);
}

export function CampaignChannelToJSONTyped(value?: CampaignChannel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'guid': value['guid'],
        'campaign_guid': value['campaign_guid'],
        'channel_guid': value['channel_guid'],
        'channel_name': value['channel_name'],
        'channel_bitlinks': ChannelBitlinksToJSON(value['channel_bitlinks']),
    };
}

