/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignChannelClicks } from './CampaignChannelClicks';
import {
    CampaignChannelClicksFromJSON,
    CampaignChannelClicksFromJSONTyped,
    CampaignChannelClicksToJSON,
    CampaignChannelClicksToJSONTyped,
} from './CampaignChannelClicks';

/**
 * 
 * @export
 * @interface CampaignClicksData
 */
export interface CampaignClicksData {
    /**
     * 
     * @type {string}
     * @memberof CampaignClicksData
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignClicksData
     */
    brand_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignClicksData
     */
    created_by?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignClicksData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignClicksData
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignClicksData
     */
    created_ts?: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignClicksData
     */
    total_clicks?: number;
    /**
     * 
     * @type {Array<CampaignChannelClicks>}
     * @memberof CampaignClicksData
     */
    campaign_channels?: Array<CampaignChannelClicks>;
}

/**
 * Check if a given object implements the CampaignClicksData interface.
 */
export function instanceOfCampaignClicksData(value: object): value is CampaignClicksData {
    return true;
}

export function CampaignClicksDataFromJSON(json: any): CampaignClicksData {
    return CampaignClicksDataFromJSONTyped(json, false);
}

export function CampaignClicksDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignClicksData {
    if (json == null) {
        return json;
    }
    return {
        
        'guid': json['guid'] == null ? undefined : json['guid'],
        'brand_guid': json['brand_guid'] == null ? undefined : json['brand_guid'],
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'created_ts': json['created_ts'] == null ? undefined : json['created_ts'],
        'total_clicks': json['total_clicks'] == null ? undefined : json['total_clicks'],
        'campaign_channels': json['campaign_channels'] == null ? undefined : ((json['campaign_channels'] as Array<any>).map(CampaignChannelClicksFromJSON)),
    };
}

export function CampaignClicksDataToJSON(json: any): CampaignClicksData {
    return CampaignClicksDataToJSONTyped(json, false);
}

export function CampaignClicksDataToJSONTyped(value?: CampaignClicksData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guid': value['guid'],
        'brand_guid': value['brand_guid'],
        'created_by': value['created_by'],
        'name': value['name'],
        'description': value['description'],
        'created_ts': value['created_ts'],
        'total_clicks': value['total_clicks'],
        'campaign_channels': value['campaign_channels'] == null ? undefined : ((value['campaign_channels'] as Array<any>).map(CampaignChannelClicksToJSON)),
    };
}

