/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Campaign
     */
    references?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    group_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    created_by?: string;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    description?: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof Campaign
     */
    created?: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof Campaign
     */
    modified?: string;
}

/**
 * Check if a given object implements the Campaign interface.
 */
export function instanceOfCampaign(value: object): value is Campaign {
    return true;
}

export function CampaignFromJSON(json: any): Campaign {
    return CampaignFromJSONTyped(json, false);
}

export function CampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): Campaign {
    if (json == null) {
        return json;
    }
    return {
        
        'references': json['references'] == null ? undefined : json['references'],
        'guid': json['guid'] == null ? undefined : json['guid'],
        'group_guid': json['group_guid'] == null ? undefined : json['group_guid'],
        'created_by': json['created_by'] == null ? undefined : json['created_by'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'modified': json['modified'] == null ? undefined : json['modified'],
    };
}

export function CampaignToJSON(json: any): Campaign {
    return CampaignToJSONTyped(json, false);
}

export function CampaignToJSONTyped(value?: Campaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'references': value['references'],
        'guid': value['guid'],
        'group_guid': value['group_guid'],
        'created_by': value['created_by'],
        'name': value['name'],
        'description': value['description'],
        'created': value['created'],
        'modified': value['modified'],
    };
}

