/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignAddBitlinkResult
 */
export interface CampaignAddBitlinkResult {
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    channel_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    bitlink_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    long_url?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CampaignAddBitlinkResult
     */
    new_channel_bitlink?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    shorten_link_error?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    channel_bitlink_error?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignAddBitlinkResult
     */
    other_link_error?: string;
}

/**
 * Check if a given object implements the CampaignAddBitlinkResult interface.
 */
export function instanceOfCampaignAddBitlinkResult(value: object): value is CampaignAddBitlinkResult {
    return true;
}

export function CampaignAddBitlinkResultFromJSON(json: any): CampaignAddBitlinkResult {
    return CampaignAddBitlinkResultFromJSONTyped(json, false);
}

export function CampaignAddBitlinkResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignAddBitlinkResult {
    if (json == null) {
        return json;
    }
    return {
        
        'channel_guid': json['channel_guid'] == null ? undefined : json['channel_guid'],
        'bitlink_id': json['bitlink_id'] == null ? undefined : json['bitlink_id'],
        'long_url': json['long_url'] == null ? undefined : json['long_url'],
        'url': json['url'] == null ? undefined : json['url'],
        'new_channel_bitlink': json['new_channel_bitlink'] == null ? undefined : json['new_channel_bitlink'],
        'shorten_link_error': json['shorten_link_error'] == null ? undefined : json['shorten_link_error'],
        'channel_bitlink_error': json['channel_bitlink_error'] == null ? undefined : json['channel_bitlink_error'],
        'other_link_error': json['other_link_error'] == null ? undefined : json['other_link_error'],
    };
}

export function CampaignAddBitlinkResultToJSON(json: any): CampaignAddBitlinkResult {
    return CampaignAddBitlinkResultToJSONTyped(json, false);
}

export function CampaignAddBitlinkResultToJSONTyped(value?: CampaignAddBitlinkResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_guid': value['channel_guid'],
        'bitlink_id': value['bitlink_id'],
        'long_url': value['long_url'],
        'url': value['url'],
        'new_channel_bitlink': value['new_channel_bitlink'],
        'shorten_link_error': value['shorten_link_error'],
        'channel_bitlink_error': value['channel_bitlink_error'],
        'other_link_error': value['other_link_error'],
    };
}

