/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClicksByCitiesFacet
 */
export interface ClicksByCitiesFacet {
    /**
     * 
     * @type {string}
     * @memberof ClicksByCitiesFacet
     */
    city?: string;
    /**
     * 
     * @type {number}
     * @memberof ClicksByCitiesFacet
     */
    clicks?: number;
    /**
     * 
     * @type {string}
     * @memberof ClicksByCitiesFacet
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof ClicksByCitiesFacet
     */
    subregion?: string;
    /**
     * 
     * @type {string}
     * @memberof ClicksByCitiesFacet
     */
    country?: string;
}

/**
 * Check if a given object implements the ClicksByCitiesFacet interface.
 */
export function instanceOfClicksByCitiesFacet(value: object): value is ClicksByCitiesFacet {
    return true;
}

export function ClicksByCitiesFacetFromJSON(json: any): ClicksByCitiesFacet {
    return ClicksByCitiesFacetFromJSONTyped(json, false);
}

export function ClicksByCitiesFacetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClicksByCitiesFacet {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'region': json['region'] == null ? undefined : json['region'],
        'subregion': json['subregion'] == null ? undefined : json['subregion'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function ClicksByCitiesFacetToJSON(json: any): ClicksByCitiesFacet {
    return ClicksByCitiesFacetToJSONTyped(json, false);
}

export function ClicksByCitiesFacetToJSONTyped(value?: ClicksByCitiesFacet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'clicks': value['clicks'],
        'region': value['region'],
        'subregion': value['subregion'],
        'country': value['country'],
    };
}

