/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddOnUsage } from './AddOnUsage';
import {
    AddOnUsageFromJSON,
    AddOnUsageFromJSONTyped,
    AddOnUsageToJSON,
    AddOnUsageToJSONTyped,
} from './AddOnUsage';

/**
 * 
 * @export
 * @interface ConsumableFeatureFull
 */
export interface ConsumableFeatureFull {
    /**
     * ISO_TIMESTAMP
     * @type {string}
     * @memberof ConsumableFeatureFull
     */
    created?: string;
    /**
     * ISO_TIMESTAMP
     * @type {string}
     * @memberof ConsumableFeatureFull
     */
    modified?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumableFeatureFull
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumableFeatureFull
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ConsumableFeatureFull
     */
    limit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConsumableFeatureFull
     */
    is_tier_default?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConsumableFeatureFull
     */
    is_enforced?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConsumableFeatureFull
     */
    is_limited?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConsumableFeatureFull
     */
    count?: number;
    /**
     * 
     * @type {AddOnUsage}
     * @memberof ConsumableFeatureFull
     */
    add_on_usage?: AddOnUsage;
}

/**
 * Check if a given object implements the ConsumableFeatureFull interface.
 */
export function instanceOfConsumableFeatureFull(value: object): value is ConsumableFeatureFull {
    return true;
}

export function ConsumableFeatureFullFromJSON(json: any): ConsumableFeatureFull {
    return ConsumableFeatureFullFromJSONTyped(json, false);
}

export function ConsumableFeatureFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumableFeatureFull {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'modified': json['modified'] == null ? undefined : json['modified'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'is_tier_default': json['is_tier_default'] == null ? undefined : json['is_tier_default'],
        'is_enforced': json['is_enforced'] == null ? undefined : json['is_enforced'],
        'is_limited': json['is_limited'] == null ? undefined : json['is_limited'],
        'count': json['count'] == null ? undefined : json['count'],
        'add_on_usage': json['add_on_usage'] == null ? undefined : AddOnUsageFromJSON(json['add_on_usage']),
    };
}

export function ConsumableFeatureFullToJSON(json: any): ConsumableFeatureFull {
    return ConsumableFeatureFullToJSONTyped(json, false);
}

export function ConsumableFeatureFullToJSONTyped(value?: ConsumableFeatureFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'modified': value['modified'],
        'id': value['id'],
        'name': value['name'],
        'limit': value['limit'],
        'is_tier_default': value['is_tier_default'],
        'is_enforced': value['is_enforced'],
        'is_limited': value['is_limited'],
        'count': value['count'],
        'add_on_usage': AddOnUsageToJSON(value['add_on_usage']),
    };
}

