/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentRequestSocial
 */
export interface ContentRequestSocial {
    /**
     * 
     * @type {string}
     * @memberof ContentRequestSocial
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequestSocial
     */
    channel?: string;
}

/**
 * Check if a given object implements the ContentRequestSocial interface.
 */
export function instanceOfContentRequestSocial(value: object): value is ContentRequestSocial {
    return true;
}

export function ContentRequestSocialFromJSON(json: any): ContentRequestSocial {
    return ContentRequestSocialFromJSONTyped(json, false);
}

export function ContentRequestSocialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentRequestSocial {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'channel': json['channel'] == null ? undefined : json['channel'],
    };
}

export function ContentRequestSocialToJSON(json: any): ContentRequestSocial {
    return ContentRequestSocialToJSONTyped(json, false);
}

export function ContentRequestSocialToJSONTyped(value?: ContentRequestSocial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'channel': value['channel'],
    };
}

