/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountItem
 */
export interface CountItem {
    /**
     * 
     * @type {string}
     * @memberof CountItem
     */
    ts?: string;
    /**
     * 
     * @type {number}
     * @memberof CountItem
     */
    count?: number;
}

/**
 * Check if a given object implements the CountItem interface.
 */
export function instanceOfCountItem(value: object): value is CountItem {
    return true;
}

export function CountItemFromJSON(json: any): CountItem {
    return CountItemFromJSONTyped(json, false);
}

export function CountItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountItem {
    if (json == null) {
        return json;
    }
    return {
        
        'ts': json['ts'] == null ? undefined : json['ts'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function CountItemToJSON(json: any): CountItem {
    return CountItemToJSONTyped(json, false);
}

export function CountItemToJSONTyped(value?: CountItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ts': value['ts'],
        'count': value['count'],
    };
}

