/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModuleSettings } from './ModuleSettings';
import {
    ModuleSettingsFromJSON,
    ModuleSettingsFromJSONTyped,
    ModuleSettingsToJSON,
    ModuleSettingsToJSONTyped,
} from './ModuleSettings';

/**
 * 
 * @export
 * @interface CreateAnalyticsModule
 */
export interface CreateAnalyticsModule {
    /**
     * 
     * @type {ModuleSettings}
     * @memberof CreateAnalyticsModule
     */
    module_settings?: ModuleSettings;
    /**
     * 
     * @type {string}
     * @memberof CreateAnalyticsModule
     */
    group_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAnalyticsModule
     */
    report_guid?: string;
}

/**
 * Check if a given object implements the CreateAnalyticsModule interface.
 */
export function instanceOfCreateAnalyticsModule(value: object): value is CreateAnalyticsModule {
    return true;
}

export function CreateAnalyticsModuleFromJSON(json: any): CreateAnalyticsModule {
    return CreateAnalyticsModuleFromJSONTyped(json, false);
}

export function CreateAnalyticsModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsModule {
    if (json == null) {
        return json;
    }
    return {
        
        'module_settings': json['module_settings'] == null ? undefined : ModuleSettingsFromJSON(json['module_settings']),
        'group_guid': json['group_guid'] == null ? undefined : json['group_guid'],
        'report_guid': json['report_guid'] == null ? undefined : json['report_guid'],
    };
}

export function CreateAnalyticsModuleToJSON(json: any): CreateAnalyticsModule {
    return CreateAnalyticsModuleToJSONTyped(json, false);
}

export function CreateAnalyticsModuleToJSONTyped(value?: CreateAnalyticsModule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'module_settings': ModuleSettingsToJSON(value['module_settings']),
        'group_guid': value['group_guid'],
        'report_guid': value['report_guid'],
    };
}

