/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @deprecated LL-2507
 * @export
 * @interface CreateLaunchpad
 */
export interface CreateLaunchpad {
    /**
     * 
     * @type {string}
     * @memberof CreateLaunchpad
     */
    group_guid: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLaunchpad
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLaunchpad
     */
    keyword: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLaunchpad
     */
    uri?: string;
}

/**
 * Check if a given object implements the CreateLaunchpad interface.
 */
export function instanceOfCreateLaunchpad(value: object): value is CreateLaunchpad {
    if (!('group_guid' in value) || value['group_guid'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('keyword' in value) || value['keyword'] === undefined) return false;
    return true;
}

export function CreateLaunchpadFromJSON(json: any): CreateLaunchpad {
    return CreateLaunchpadFromJSONTyped(json, false);
}

export function CreateLaunchpadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLaunchpad {
    if (json == null) {
        return json;
    }
    return {
        
        'group_guid': json['group_guid'],
        'domain': json['domain'],
        'keyword': json['keyword'],
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function CreateLaunchpadToJSON(json: any): CreateLaunchpad {
    return CreateLaunchpadToJSONTyped(json, false);
}

export function CreateLaunchpadToJSONTyped(value?: CreateLaunchpad | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_guid': value['group_guid'],
        'domain': value['domain'],
        'keyword': value['keyword'],
        'uri': value['uri'],
    };
}

