/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicSSLCert } from './PublicSSLCert';
import {
    PublicSSLCertFromJSON,
    PublicSSLCertFromJSONTyped,
    PublicSSLCertToJSON,
    PublicSSLCertToJSONTyped,
} from './PublicSSLCert';
import type { MinimalDeeplinkApp } from './MinimalDeeplinkApp';
import {
    MinimalDeeplinkAppFromJSON,
    MinimalDeeplinkAppFromJSONTyped,
    MinimalDeeplinkAppToJSON,
    MinimalDeeplinkAppToJSONTyped,
} from './MinimalDeeplinkApp';

/**
 * information about given custom domain
 * @export
 * @interface CustomDomainBody
 */
export interface CustomDomainBody {
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    custom_domain?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    is_active?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomDomainBody
     */
    group_guids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    ssl_configuration_error?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    configuration_last_check_ts?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    root_redirect?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    https_bitlinks?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    ssl_autoconfigure_error?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    https_enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    hsts_enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CustomDomainBody
     */
    created?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    wildcard_redirect?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    validation_status?: CustomDomainBodyValidationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainBody
     */
    validation_error?: string;
    /**
     * 
     * @type {Array<MinimalDeeplinkApp>}
     * @memberof CustomDomainBody
     */
    deeplink_apps?: Array<MinimalDeeplinkApp>;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainBody
     */
    upgrade_insecure_requests?: boolean;
    /**
     * 
     * @type {PublicSSLCert}
     * @memberof CustomDomainBody
     */
    ssl_cert?: PublicSSLCert;
}

/**
* @export
* @enum {string}
*/
export enum CustomDomainBodyValidationStatusEnum {
    ok = 'ok',
    pending = 'pending',
    error = 'error'
}


/**
 * Check if a given object implements the CustomDomainBody interface.
 */
export function instanceOfCustomDomainBody(value: object): value is CustomDomainBody {
    return true;
}

export function CustomDomainBodyFromJSON(json: any): CustomDomainBody {
    return CustomDomainBodyFromJSONTyped(json, false);
}

export function CustomDomainBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainBody {
    if (json == null) {
        return json;
    }
    return {
        
        'custom_domain': json['custom_domain'] == null ? undefined : json['custom_domain'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'group_guids': json['group_guids'] == null ? undefined : json['group_guids'],
        'ssl_configuration_error': json['ssl_configuration_error'] == null ? undefined : json['ssl_configuration_error'],
        'configuration_last_check_ts': json['configuration_last_check_ts'] == null ? undefined : json['configuration_last_check_ts'],
        'root_redirect': json['root_redirect'] == null ? undefined : json['root_redirect'],
        'https_bitlinks': json['https_bitlinks'] == null ? undefined : json['https_bitlinks'],
        'ssl_autoconfigure_error': json['ssl_autoconfigure_error'] == null ? undefined : json['ssl_autoconfigure_error'],
        'https_enabled': json['https_enabled'] == null ? undefined : json['https_enabled'],
        'hsts_enabled': json['hsts_enabled'] == null ? undefined : json['hsts_enabled'],
        'created': json['created'] == null ? undefined : json['created'],
        'wildcard_redirect': json['wildcard_redirect'] == null ? undefined : json['wildcard_redirect'],
        'validation_status': json['validation_status'] == null ? undefined : json['validation_status'],
        'validation_error': json['validation_error'] == null ? undefined : json['validation_error'],
        'deeplink_apps': json['deeplink_apps'] == null ? undefined : ((json['deeplink_apps'] as Array<any>).map(MinimalDeeplinkAppFromJSON)),
        'upgrade_insecure_requests': json['upgrade_insecure_requests'] == null ? undefined : json['upgrade_insecure_requests'],
        'ssl_cert': json['ssl_cert'] == null ? undefined : PublicSSLCertFromJSON(json['ssl_cert']),
    };
}

export function CustomDomainBodyToJSON(json: any): CustomDomainBody {
    return CustomDomainBodyToJSONTyped(json, false);
}

export function CustomDomainBodyToJSONTyped(value?: CustomDomainBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_domain': value['custom_domain'],
        'is_active': value['is_active'],
        'group_guids': value['group_guids'],
        'ssl_configuration_error': value['ssl_configuration_error'],
        'configuration_last_check_ts': value['configuration_last_check_ts'],
        'root_redirect': value['root_redirect'],
        'https_bitlinks': value['https_bitlinks'],
        'ssl_autoconfigure_error': value['ssl_autoconfigure_error'],
        'https_enabled': value['https_enabled'],
        'hsts_enabled': value['hsts_enabled'],
        'created': value['created'],
        'wildcard_redirect': value['wildcard_redirect'],
        'validation_status': value['validation_status'],
        'validation_error': value['validation_error'],
        'deeplink_apps': value['deeplink_apps'] == null ? undefined : ((value['deeplink_apps'] as Array<any>).map(MinimalDeeplinkAppToJSON)),
        'upgrade_insecure_requests': value['upgrade_insecure_requests'],
        'ssl_cert': PublicSSLCertToJSON(value['ssl_cert']),
    };
}

