/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecideRequest
 */
export interface DecideRequest {
    /**
     * 
     * @type {string}
     * @memberof DecideRequest
     */
    flag: string;
    /**
     * 
     * @type {string}
     * @memberof DecideRequest
     */
    org_guid: string;
    /**
     * 
     * @type {string}
     * @memberof DecideRequest
     */
    action?: string;
}

/**
 * Check if a given object implements the DecideRequest interface.
 */
export function instanceOfDecideRequest(value: object): value is DecideRequest {
    if (!('flag' in value) || value['flag'] === undefined) return false;
    if (!('org_guid' in value) || value['org_guid'] === undefined) return false;
    return true;
}

export function DecideRequestFromJSON(json: any): DecideRequest {
    return DecideRequestFromJSONTyped(json, false);
}

export function DecideRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecideRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'flag': json['flag'],
        'org_guid': json['org_guid'],
        'action': json['action'] == null ? undefined : json['action'],
    };
}

export function DecideRequestToJSON(json: any): DecideRequest {
    return DecideRequestToJSONTyped(json, false);
}

export function DecideRequestToJSONTyped(value?: DecideRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'flag': value['flag'],
        'org_guid': value['org_guid'],
        'action': value['action'],
    };
}

