/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * the tier default values for a single access feature
 * @export
 * @interface DefaultAccessFeature
 */
export interface DefaultAccessFeature {
    /**
     * 
     * @type {string}
     * @memberof DefaultAccessFeature
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DefaultAccessFeature
     */
    has_access?: boolean;
}

/**
 * Check if a given object implements the DefaultAccessFeature interface.
 */
export function instanceOfDefaultAccessFeature(value: object): value is DefaultAccessFeature {
    return true;
}

export function DefaultAccessFeatureFromJSON(json: any): DefaultAccessFeature {
    return DefaultAccessFeatureFromJSONTyped(json, false);
}

export function DefaultAccessFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultAccessFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'has_access': json['has_access'] == null ? undefined : json['has_access'],
    };
}

export function DefaultAccessFeatureToJSON(json: any): DefaultAccessFeature {
    return DefaultAccessFeatureToJSONTyped(json, false);
}

export function DefaultAccessFeatureToJSONTyped(value?: DefaultAccessFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'has_access': value['has_access'],
    };
}

