/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * the tier default values for a single consumable feature
 * @export
 * @interface DefaultConsumableFeature
 */
export interface DefaultConsumableFeature {
    /**
     * 
     * @type {string}
     * @memberof DefaultConsumableFeature
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DefaultConsumableFeature
     */
    limit?: number;
}

/**
 * Check if a given object implements the DefaultConsumableFeature interface.
 */
export function instanceOfDefaultConsumableFeature(value: object): value is DefaultConsumableFeature {
    return true;
}

export function DefaultConsumableFeatureFromJSON(json: any): DefaultConsumableFeature {
    return DefaultConsumableFeatureFromJSONTyped(json, false);
}

export function DefaultConsumableFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultConsumableFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function DefaultConsumableFeatureToJSON(json: any): DefaultConsumableFeature {
    return DefaultConsumableFeatureToJSONTyped(json, false);
}

export function DefaultConsumableFeatureToJSONTyped(value?: DefaultConsumableFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'limit': value['limit'],
    };
}

