/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeletedQRCodeResponse
 */
export interface DeletedQRCodeResponse {
    /**
     * The QR code's id, as a guid
     * @type {string}
     * @memberof DeletedQRCodeResponse
     */
    qrcode_id?: string;
}

/**
 * Check if a given object implements the DeletedQRCodeResponse interface.
 */
export function instanceOfDeletedQRCodeResponse(value: object): value is DeletedQRCodeResponse {
    return true;
}

export function DeletedQRCodeResponseFromJSON(json: any): DeletedQRCodeResponse {
    return DeletedQRCodeResponseFromJSONTyped(json, false);
}

export function DeletedQRCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletedQRCodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qrcode_id': json['qrcode_id'] == null ? undefined : json['qrcode_id'],
    };
}

export function DeletedQRCodeResponseToJSON(json: any): DeletedQRCodeResponse {
    return DeletedQRCodeResponseToJSONTyped(json, false);
}

export function DeletedQRCodeResponseToJSONTyped(value?: DeletedQRCodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrcode_id': value['qrcode_id'],
    };
}

