/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Discount
 */
export interface Discount {
    /**
     * 
     * @type {string}
     * @memberof Discount
     */
    coupon_duration?: string;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    amount_off?: number;
    /**
     * 
     * @type {number}
     * @memberof Discount
     */
    percent_off?: number;
}

/**
 * Check if a given object implements the Discount interface.
 */
export function instanceOfDiscount(value: object): value is Discount {
    return true;
}

export function DiscountFromJSON(json: any): Discount {
    return DiscountFromJSONTyped(json, false);
}

export function DiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discount {
    if (json == null) {
        return json;
    }
    return {
        
        'coupon_duration': json['coupon_duration'] == null ? undefined : json['coupon_duration'],
        'amount_off': json['amount_off'] == null ? undefined : json['amount_off'],
        'percent_off': json['percent_off'] == null ? undefined : json['percent_off'],
    };
}

export function DiscountToJSON(json: any): Discount {
    return DiscountToJSONTyped(json, false);
}

export function DiscountToJSONTyped(value?: Discount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coupon_duration': value['coupon_duration'],
        'amount_off': value['amount_off'],
        'percent_off': value['percent_off'],
    };
}

