/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainAgreement
 */
export interface DomainAgreement {
    /**
     * 
     * @type {string}
     * @memberof DomainAgreement
     */
    agreement_key?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAgreement
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAgreement
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAgreement
     */
    url?: string;
}

/**
 * Check if a given object implements the DomainAgreement interface.
 */
export function instanceOfDomainAgreement(value: object): value is DomainAgreement {
    return true;
}

export function DomainAgreementFromJSON(json: any): DomainAgreement {
    return DomainAgreementFromJSONTyped(json, false);
}

export function DomainAgreementFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAgreement {
    if (json == null) {
        return json;
    }
    return {
        
        'agreement_key': json['agreement_key'] == null ? undefined : json['agreement_key'],
        'content': json['content'] == null ? undefined : json['content'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DomainAgreementToJSON(json: any): DomainAgreement {
    return DomainAgreementToJSONTyped(json, false);
}

export function DomainAgreementToJSONTyped(value?: DomainAgreement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreement_key': value['agreement_key'],
        'content': value['content'],
        'title': value['title'],
        'url': value['url'],
    };
}

