/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Engagement } from './Engagement';
import {
    EngagementFromJSON,
    EngagementFromJSONTyped,
    EngagementToJSON,
    EngagementToJSONTyped,
} from './Engagement';

/**
 * 
 * @export
 * @interface Engagements
 */
export interface Engagements {
    /**
     * 
     * @type {number}
     * @memberof Engagements
     */
    engagement_count?: number;
    /**
     * 
     * @type {Engagement}
     * @memberof Engagements
     */
    engagements?: Engagement;
    /**
     * 
     * @type {string}
     * @memberof Engagements
     */
    date?: string;
}

/**
 * Check if a given object implements the Engagements interface.
 */
export function instanceOfEngagements(value: object): value is Engagements {
    return true;
}

export function EngagementsFromJSON(json: any): Engagements {
    return EngagementsFromJSONTyped(json, false);
}

export function EngagementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Engagements {
    if (json == null) {
        return json;
    }
    return {
        
        'engagement_count': json['engagement_count'] == null ? undefined : json['engagement_count'],
        'engagements': json['engagements'] == null ? undefined : EngagementFromJSON(json['engagements']),
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function EngagementsToJSON(json: any): Engagements {
    return EngagementsToJSONTyped(json, false);
}

export function EngagementsToJSONTyped(value?: Engagements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'engagement_count': value['engagement_count'],
        'engagements': EngagementToJSON(value['engagements']),
        'date': value['date'],
    };
}

