/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacetCountItem
 */
export interface FacetCountItem {
    /**
     * 
     * @type {number}
     * @memberof FacetCountItem
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof FacetCountItem
     */
    value?: string;
}

/**
 * Check if a given object implements the FacetCountItem interface.
 */
export function instanceOfFacetCountItem(value: object): value is FacetCountItem {
    return true;
}

export function FacetCountItemFromJSON(json: any): FacetCountItem {
    return FacetCountItemFromJSONTyped(json, false);
}

export function FacetCountItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetCountItem {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function FacetCountItemToJSON(json: any): FacetCountItem {
    return FacetCountItemToJSONTyped(json, false);
}

export function FacetCountItemToJSONTyped(value?: FacetCountItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'value': value['value'],
    };
}

