/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormSelectOptions } from './FormSelectOptions';
import {
    FormSelectOptionsFromJSON,
    FormSelectOptionsFromJSONTyped,
    FormSelectOptionsToJSON,
    FormSelectOptionsToJSONTyped,
} from './FormSelectOptions';

/**
 * 
 * @export
 * @interface FormConfig
 */
export interface FormConfig {
    /**
     * 
     * @type {Array<FormSelectOptions>}
     * @memberof FormConfig
     */
    options?: Array<FormSelectOptions>;
}

/**
 * Check if a given object implements the FormConfig interface.
 */
export function instanceOfFormConfig(value: object): value is FormConfig {
    return true;
}

export function FormConfigFromJSON(json: any): FormConfig {
    return FormConfigFromJSONTyped(json, false);
}

export function FormConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(FormSelectOptionsFromJSON)),
    };
}

export function FormConfigToJSON(json: any): FormConfig {
    return FormConfigToJSONTyped(json, false);
}

export function FormConfigToJSONTyped(value?: FormConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(FormSelectOptionsToJSON)),
    };
}

