/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoIP
 */
export interface GeoIP {
    /**
     * 
     * @type {string}
     * @memberof GeoIP
     */
    country_code?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GeoIP
     */
    is_in_european_union?: boolean;
}

/**
 * Check if a given object implements the GeoIP interface.
 */
export function instanceOfGeoIP(value: object): value is GeoIP {
    return true;
}

export function GeoIPFromJSON(json: any): GeoIP {
    return GeoIPFromJSONTyped(json, false);
}

export function GeoIPFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoIP {
    if (json == null) {
        return json;
    }
    return {
        
        'country_code': json['country_code'] == null ? undefined : json['country_code'],
        'is_in_european_union': json['is_in_european_union'] == null ? undefined : json['is_in_european_union'],
    };
}

export function GeoIPToJSON(json: any): GeoIP {
    return GeoIPToJSONTyped(json, false);
}

export function GeoIPToJSONTyped(value?: GeoIP | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country_code': value['country_code'],
        'is_in_european_union': value['is_in_european_union'],
    };
}

