/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAggregateSitesOverview200Response
 */
export interface GetAggregateSitesOverview200Response {
    /**
     * 
     * @type {number}
     * @memberof GetAggregateSitesOverview200Response
     */
    views?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregateSitesOverview200Response
     */
    clicks?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAggregateSitesOverview200Response
     */
    info?: string;
}

/**
 * Check if a given object implements the GetAggregateSitesOverview200Response interface.
 */
export function instanceOfGetAggregateSitesOverview200Response(value: object): value is GetAggregateSitesOverview200Response {
    return true;
}

export function GetAggregateSitesOverview200ResponseFromJSON(json: any): GetAggregateSitesOverview200Response {
    return GetAggregateSitesOverview200ResponseFromJSONTyped(json, false);
}

export function GetAggregateSitesOverview200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAggregateSitesOverview200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'views': json['views'] == null ? undefined : json['views'],
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'info': json['info'] == null ? undefined : json['info'],
    };
}

export function GetAggregateSitesOverview200ResponseToJSON(json: any): GetAggregateSitesOverview200Response {
    return GetAggregateSitesOverview200ResponseToJSONTyped(json, false);
}

export function GetAggregateSitesOverview200ResponseToJSONTyped(value?: GetAggregateSitesOverview200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'views': value['views'],
        'clicks': value['clicks'],
        'info': value['info'],
    };
}

