/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GradientColor
 */
export interface GradientColor {
    /**
     * A color in hexadecimal format to be used in one of the gradient's <stop> elements
     * @type {string}
     * @memberof GradientColor
     */
    color?: string;
    /**
     * A number between 0-100 denoting the offset of the gradient color, interpreted as a percentage
     * @type {number}
     * @memberof GradientColor
     */
    offset?: number;
}

/**
 * Check if a given object implements the GradientColor interface.
 */
export function instanceOfGradientColor(value: object): value is GradientColor {
    return true;
}

export function GradientColorFromJSON(json: any): GradientColor {
    return GradientColorFromJSONTyped(json, false);
}

export function GradientColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradientColor {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function GradientColorToJSON(json: any): GradientColor {
    return GradientColorToJSONTyped(json, false);
}

export function GradientColorToJSONTyped(value?: GradientColor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'offset': value['offset'],
    };
}

