/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUpdate
 */
export interface GroupUpdate {
    /**
     * 
     * @type {string}
     * @memberof GroupUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupUpdate
     */
    organization_guid?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupUpdate
     */
    bsds?: Array<string>;
}

/**
 * Check if a given object implements the GroupUpdate interface.
 */
export function instanceOfGroupUpdate(value: object): value is GroupUpdate {
    return true;
}

export function GroupUpdateFromJSON(json: any): GroupUpdate {
    return GroupUpdateFromJSONTyped(json, false);
}

export function GroupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'organization_guid': json['organization_guid'] == null ? undefined : json['organization_guid'],
        'bsds': json['bsds'] == null ? undefined : json['bsds'],
    };
}

export function GroupUpdateToJSON(json: any): GroupUpdate {
    return GroupUpdateToJSONTyped(json, false);
}

export function GroupUpdateToJSONTyped(value?: GroupUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'organization_guid': value['organization_guid'],
        'bsds': value['bsds'],
    };
}

