/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountItem } from './CountItem';
import {
    CountItemFromJSON,
    CountItemFromJSONTyped,
    CountItemToJSON,
    CountItemToJSONTyped,
} from './CountItem';

/**
 * 
 * @export
 * @interface GroupClicks
 */
export interface GroupClicks {
    /**
     * 
     * @type {string}
     * @memberof GroupClicks
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupClicks
     */
    units?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupClicks
     */
    unit_reference?: string;
    /**
     * 
     * @type {Array<CountItem>}
     * @memberof GroupClicks
     */
    data?: Array<CountItem>;
}

/**
 * Check if a given object implements the GroupClicks interface.
 */
export function instanceOfGroupClicks(value: object): value is GroupClicks {
    return true;
}

export function GroupClicksFromJSON(json: any): GroupClicks {
    return GroupClicksFromJSONTyped(json, false);
}

export function GroupClicksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupClicks {
    if (json == null) {
        return json;
    }
    return {
        
        'unit': json['unit'] == null ? undefined : json['unit'],
        'units': json['units'] == null ? undefined : json['units'],
        'unit_reference': json['unit_reference'] == null ? undefined : json['unit_reference'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CountItemFromJSON)),
    };
}

export function GroupClicksToJSON(json: any): GroupClicks {
    return GroupClicksToJSONTyped(json, false);
}

export function GroupClicksToJSONTyped(value?: GroupClicks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unit': value['unit'],
        'units': value['units'],
        'unit_reference': value['unit_reference'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CountItemToJSON)),
    };
}

