/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoricalUsage
 */
export interface HistoricalUsage {
    /**
     * the usage count during the time period
     * @type {number}
     * @memberof HistoricalUsage
     */
    count?: number;
    /**
     * ISO_TIMESTAMP of the beginning of the time period
     * @type {string}
     * @memberof HistoricalUsage
     */
    unit_start?: string;
}

/**
 * Check if a given object implements the HistoricalUsage interface.
 */
export function instanceOfHistoricalUsage(value: object): value is HistoricalUsage {
    return true;
}

export function HistoricalUsageFromJSON(json: any): HistoricalUsage {
    return HistoricalUsageFromJSONTyped(json, false);
}

export function HistoricalUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoricalUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'unit_start': json['unit_start'] == null ? undefined : json['unit_start'],
    };
}

export function HistoricalUsageToJSON(json: any): HistoricalUsage {
    return HistoricalUsageToJSONTyped(json, false);
}

export function HistoricalUsageToJSONTyped(value?: HistoricalUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'unit_start': value['unit_start'],
    };
}

