/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageContent
 */
export interface ImageContent {
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    image_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    image_url?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    crop?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    aspect_ratio?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    link_title?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    bitlink_id?: string;
}

/**
 * Check if a given object implements the ImageContent interface.
 */
export function instanceOfImageContent(value: object): value is ImageContent {
    return true;
}

export function ImageContentFromJSON(json: any): ImageContent {
    return ImageContentFromJSONTyped(json, false);
}

export function ImageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageContent {
    if (json == null) {
        return json;
    }
    return {
        
        'image_guid': json['image_guid'] == null ? undefined : json['image_guid'],
        'image_url': json['image_url'] == null ? undefined : json['image_url'],
        'crop': json['crop'] == null ? undefined : json['crop'],
        'aspect_ratio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'link_title': json['link_title'] == null ? undefined : json['link_title'],
        'description': json['description'] == null ? undefined : json['description'],
        'bitlink_id': json['bitlink_id'] == null ? undefined : json['bitlink_id'],
    };
}

export function ImageContentToJSON(json: any): ImageContent {
    return ImageContentToJSONTyped(json, false);
}

export function ImageContentToJSONTyped(value?: ImageContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_guid': value['image_guid'],
        'image_url': value['image_url'],
        'crop': value['crop'],
        'aspect_ratio': value['aspect_ratio'],
        'link_title': value['link_title'],
        'description': value['description'],
        'bitlink_id': value['bitlink_id'],
    };
}

