/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageCrop } from './ImageCrop';
import {
    ImageCropFromJSON,
    ImageCropFromJSONTyped,
    ImageCropToJSON,
    ImageCropToJSONTyped,
} from './ImageCrop';

/**
 * 
 * @export
 * @interface ImageUpdate
 */
export interface ImageUpdate {
    /**
     * 
     * @type {string}
     * @memberof ImageUpdate
     */
    group_guid?: string;
    /**
     * 
     * @type {ImageCrop}
     * @memberof ImageUpdate
     */
    crop?: ImageCrop;
}

/**
 * Check if a given object implements the ImageUpdate interface.
 */
export function instanceOfImageUpdate(value: object): value is ImageUpdate {
    return true;
}

export function ImageUpdateFromJSON(json: any): ImageUpdate {
    return ImageUpdateFromJSONTyped(json, false);
}

export function ImageUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'group_guid': json['group_guid'] == null ? undefined : json['group_guid'],
        'crop': json['crop'] == null ? undefined : ImageCropFromJSON(json['crop']),
    };
}

export function ImageUpdateToJSON(json: any): ImageUpdate {
    return ImageUpdateToJSONTyped(json, false);
}

export function ImageUpdateToJSONTyped(value?: ImageUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_guid': value['group_guid'],
        'crop': ImageCropToJSON(value['crop']),
    };
}

