/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageCropPoint } from './ImageCropPoint';
import {
    ImageCropPointFromJSON,
    ImageCropPointFromJSONTyped,
    ImageCropPointToJSON,
    ImageCropPointToJSONTyped,
} from './ImageCropPoint';

/**
 * 
 * @export
 * @interface ImageCrop
 */
export interface ImageCrop {
    /**
     * 
     * @type {ImageCropPoint}
     * @memberof ImageCrop
     */
    min?: ImageCropPoint;
    /**
     * 
     * @type {ImageCropPoint}
     * @memberof ImageCrop
     */
    max?: ImageCropPoint;
}

/**
 * Check if a given object implements the ImageCrop interface.
 */
export function instanceOfImageCrop(value: object): value is ImageCrop {
    return true;
}

export function ImageCropFromJSON(json: any): ImageCrop {
    return ImageCropFromJSONTyped(json, false);
}

export function ImageCropFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageCrop {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function ImageCropToJSON(json: any): ImageCrop {
    return ImageCropToJSONTyped(json, false);
}

export function ImageCropToJSONTyped(value?: ImageCrop | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
    };
}

