/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationsError
 */
export interface InvitationsError {
    /**
     * 
     * @type {string}
     * @memberof InvitationsError
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvitationsError
     */
    emails?: Array<string>;
}

/**
 * Check if a given object implements the InvitationsError interface.
 */
export function instanceOfInvitationsError(value: object): value is InvitationsError {
    return true;
}

export function InvitationsErrorFromJSON(json: any): InvitationsError {
    return InvitationsErrorFromJSONTyped(json, false);
}

export function InvitationsErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationsError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'emails': json['emails'] == null ? undefined : json['emails'],
    };
}

export function InvitationsErrorToJSON(json: any): InvitationsError {
    return InvitationsErrorToJSONTyped(json, false);
}

export function InvitationsErrorToJSONTyped(value?: InvitationsError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'emails': value['emails'],
    };
}

