/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LaunchpadContentSocial } from './LaunchpadContentSocial';
import {
    LaunchpadContentSocialFromJSON,
    LaunchpadContentSocialFromJSONTyped,
    LaunchpadContentSocialToJSON,
    LaunchpadContentSocialToJSONTyped,
} from './LaunchpadContentSocial';

/**
 * @deprecated LL-2507
 * @export
 * @interface LaunchpadContentSocialRequest
 */
export interface LaunchpadContentSocialRequest {
    /**
     * 
     * @type {LaunchpadContentSocial}
     * @memberof LaunchpadContentSocialRequest
     */
    content?: LaunchpadContentSocial;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentSocialRequest
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentSocialRequest
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadContentSocialRequest
     */
    is_active?: boolean;
}

/**
 * Check if a given object implements the LaunchpadContentSocialRequest interface.
 */
export function instanceOfLaunchpadContentSocialRequest(value: object): value is LaunchpadContentSocialRequest {
    return true;
}

export function LaunchpadContentSocialRequestFromJSON(json: any): LaunchpadContentSocialRequest {
    return LaunchpadContentSocialRequestFromJSONTyped(json, false);
}

export function LaunchpadContentSocialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchpadContentSocialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function LaunchpadContentSocialRequestToJSON(json: any): LaunchpadContentSocialRequest {
    return LaunchpadContentSocialRequestToJSONTyped(json, false);
}

export function LaunchpadContentSocialRequestToJSONTyped(value?: LaunchpadContentSocialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
    };
}

