/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LaunchpadContentSocial } from './LaunchpadContentSocial';
import {
    LaunchpadContentSocialFromJSON,
    LaunchpadContentSocialFromJSONTyped,
    LaunchpadContentSocialToJSON,
    LaunchpadContentSocialToJSONTyped,
} from './LaunchpadContentSocial';
import type { LaunchpadButtonTypeEnum } from './LaunchpadButtonTypeEnum';
import {
    LaunchpadButtonTypeEnumFromJSON,
    LaunchpadButtonTypeEnumFromJSONTyped,
    LaunchpadButtonTypeEnumToJSON,
    LaunchpadButtonTypeEnumToJSONTyped,
} from './LaunchpadButtonTypeEnum';

/**
 * @deprecated LL-2507
 * @export
 * @interface LaunchpadSocial
 */
export interface LaunchpadSocial {
    /**
     * 
     * @type {LaunchpadContentSocial}
     * @memberof LaunchpadSocial
     */
    content?: LaunchpadContentSocial;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    launchpad_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    button_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    digital_business_card_id?: string;
    /**
     * 
     * @type {number}
     * @memberof LaunchpadSocial
     */
    sort_order?: number;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadSocial
     */
    is_active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadSocial
     */
    is_pinned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadSocial
     */
    is_sample?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocial
     */
    title?: string;
}



/**
 * Check if a given object implements the LaunchpadSocial interface.
 */
export function instanceOfLaunchpadSocial(value: object): value is LaunchpadSocial {
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    return true;
}

export function LaunchpadSocialFromJSON(json: any): LaunchpadSocial {
    return LaunchpadSocialFromJSONTyped(json, false);
}

export function LaunchpadSocialFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchpadSocial {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : LaunchpadContentSocialFromJSON(json['content']),
        'type': json['type'] == null ? undefined : json['type'],
        'launchpad_id': json['launchpad_id'] == null ? undefined : json['launchpad_id'],
        'button_id': json['button_id'] == null ? undefined : json['button_id'],
        'digital_business_card_id': json['digital_business_card_id'] == null ? undefined : json['digital_business_card_id'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'is_sample': json['is_sample'] == null ? undefined : json['is_sample'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function LaunchpadSocialToJSON(json: any): LaunchpadSocial {
    return LaunchpadSocialToJSONTyped(json, false);
}

export function LaunchpadSocialToJSONTyped(value?: LaunchpadSocial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': LaunchpadContentSocialToJSON(value['content']),
        'type': value['type'],
        'launchpad_id': value['launchpad_id'],
        'button_id': value['button_id'],
        'digital_business_card_id': value['digital_business_card_id'],
        'sort_order': value['sort_order'],
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'is_pinned': value['is_pinned'],
        'parent': value['parent'],
        'is_sample': value['is_sample'],
        'title': value['title'],
    };
}

