/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LaunchpadButtonContent } from './LaunchpadButtonContent';
import {
    LaunchpadButtonContentFromJSON,
    LaunchpadButtonContentFromJSONTyped,
    LaunchpadButtonContentToJSON,
    LaunchpadButtonContentToJSONTyped,
} from './LaunchpadButtonContent';
import type { LaunchpadButtonTypeEnum } from './LaunchpadButtonTypeEnum';
import {
    LaunchpadButtonTypeEnumFromJSON,
    LaunchpadButtonTypeEnumFromJSONTyped,
    LaunchpadButtonTypeEnumToJSON,
    LaunchpadButtonTypeEnumToJSONTyped,
} from './LaunchpadButtonTypeEnum';
import type { TextBlockAppearanceResponse } from './TextBlockAppearanceResponse';
import {
    TextBlockAppearanceResponseFromJSON,
    TextBlockAppearanceResponseFromJSONTyped,
    TextBlockAppearanceResponseToJSON,
    TextBlockAppearanceResponseToJSONTyped,
} from './TextBlockAppearanceResponse';

/**
 * @deprecated LL-2507 use SiteBlock instead
 * @export
 * @interface LaunchpadButton
 */
export interface LaunchpadButton {
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    launchpad_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    button_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    digital_business_card_id?: string;
    /**
     * 
     * @type {number}
     * @memberof LaunchpadButton
     */
    sort_order?: number;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadButton
     */
    is_active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadButton
     */
    is_pinned?: boolean;
    /**
     * 
     * @type {LaunchpadButtonTypeEnum}
     * @memberof LaunchpadButton
     */
    type?: LaunchpadButtonTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadButton
     */
    is_sample?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    bitlink?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    long_url?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    scheme?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    keyword?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadButton
     */
    description?: string;
    /**
     * 
     * @type {LaunchpadButtonContent}
     * @memberof LaunchpadButton
     */
    content?: LaunchpadButtonContent;
    /**
     * 
     * @type {TextBlockAppearanceResponse}
     * @memberof LaunchpadButton
     */
    appearance?: TextBlockAppearanceResponse;
}



/**
 * Check if a given object implements the LaunchpadButton interface.
 */
export function instanceOfLaunchpadButton(value: object): value is LaunchpadButton {
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    return true;
}

export function LaunchpadButtonFromJSON(json: any): LaunchpadButton {
    return LaunchpadButtonFromJSONTyped(json, false);
}

export function LaunchpadButtonFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchpadButton {
    if (json == null) {
        return json;
    }
    return {
        
        'launchpad_id': json['launchpad_id'] == null ? undefined : json['launchpad_id'],
        'button_id': json['button_id'] == null ? undefined : json['button_id'],
        'digital_business_card_id': json['digital_business_card_id'] == null ? undefined : json['digital_business_card_id'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'type': json['type'] == null ? undefined : LaunchpadButtonTypeEnumFromJSON(json['type']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'is_sample': json['is_sample'] == null ? undefined : json['is_sample'],
        'title': json['title'] == null ? undefined : json['title'],
        'bitlink': json['bitlink'] == null ? undefined : json['bitlink'],
        'long_url': json['long_url'] == null ? undefined : json['long_url'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'keyword': json['keyword'] == null ? undefined : json['keyword'],
        'description': json['description'] == null ? undefined : json['description'],
        'content': json['content'] == null ? undefined : LaunchpadButtonContentFromJSON(json['content']),
        'appearance': json['appearance'] == null ? undefined : TextBlockAppearanceResponseFromJSON(json['appearance']),
    };
}

export function LaunchpadButtonToJSON(json: any): LaunchpadButton {
    return LaunchpadButtonToJSONTyped(json, false);
}

export function LaunchpadButtonToJSONTyped(value?: LaunchpadButton | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'launchpad_id': value['launchpad_id'],
        'button_id': value['button_id'],
        'digital_business_card_id': value['digital_business_card_id'],
        'sort_order': value['sort_order'],
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'is_pinned': value['is_pinned'],
        'type': LaunchpadButtonTypeEnumToJSON(value['type']),
        'parent': value['parent'],
        'is_sample': value['is_sample'],
        'title': value['title'],
        'bitlink': value['bitlink'],
        'long_url': value['long_url'],
        'scheme': value['scheme'],
        'domain': value['domain'],
        'keyword': value['keyword'],
        'description': value['description'],
        'content': LaunchpadButtonContentToJSON(value['content']),
        'appearance': TextBlockAppearanceResponseToJSON(value['appearance']),
    };
}

