/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentRequestSocial } from './ContentRequestSocial';
import {
    ContentRequestSocialFromJSON,
    ContentRequestSocialFromJSONTyped,
    ContentRequestSocialToJSON,
    ContentRequestSocialToJSONTyped,
} from './ContentRequestSocial';

/**
 * @deprecated LL-2507
 * @export
 * @interface LaunchpadSocialRequest
 */
export interface LaunchpadSocialRequest {
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocialRequest
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadSocialRequest
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadSocialRequest
     */
    is_active?: boolean;
    /**
     * 
     * @type {ContentRequestSocial}
     * @memberof LaunchpadSocialRequest
     */
    content?: ContentRequestSocial;
}

/**
 * Check if a given object implements the LaunchpadSocialRequest interface.
 */
export function instanceOfLaunchpadSocialRequest(value: object): value is LaunchpadSocialRequest {
    return true;
}

export function LaunchpadSocialRequestFromJSON(json: any): LaunchpadSocialRequest {
    return LaunchpadSocialRequestFromJSONTyped(json, false);
}

export function LaunchpadSocialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchpadSocialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function LaunchpadSocialRequestToJSON(json: any): LaunchpadSocialRequest {
    return LaunchpadSocialRequestToJSONTyped(json, false);
}

export function LaunchpadSocialRequestToJSONTyped(value?: LaunchpadSocialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'content': value['content'],
    };
}

