/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DigitalBusinessCardContent } from './DigitalBusinessCardContent';
import {
    DigitalBusinessCardContentFromJSON,
    DigitalBusinessCardContentFromJSONTyped,
    DigitalBusinessCardContentToJSON,
    DigitalBusinessCardContentToJSONTyped,
} from './DigitalBusinessCardContent';
import type { LaunchpadButtonTypeEnum } from './LaunchpadButtonTypeEnum';
import {
    LaunchpadButtonTypeEnumFromJSON,
    LaunchpadButtonTypeEnumFromJSONTyped,
    LaunchpadButtonTypeEnumToJSON,
    LaunchpadButtonTypeEnumToJSONTyped,
} from './LaunchpadButtonTypeEnum';

/**
 * @deprecated LL-2507
 * @export
 * @interface LaunchpadContentDigitalBusinessCardResponse
 */
export interface LaunchpadContentDigitalBusinessCardResponse {
    /**
     * 
     * @type {DigitalBusinessCardContent}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    content?: DigitalBusinessCardContent;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    launchpad_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    button_id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    digital_business_card_id?: string;
    /**
     * 
     * @type {number}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    sort_order?: number;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    is_active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    is_pinned?: boolean;
    /**
     * 
     * @type {LaunchpadButtonTypeEnum}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    type?: LaunchpadButtonTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    parent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    is_sample?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LaunchpadContentDigitalBusinessCardResponse
     */
    title?: string;
}



/**
 * Check if a given object implements the LaunchpadContentDigitalBusinessCardResponse interface.
 */
export function instanceOfLaunchpadContentDigitalBusinessCardResponse(value: object): value is LaunchpadContentDigitalBusinessCardResponse {
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    return true;
}

export function LaunchpadContentDigitalBusinessCardResponseFromJSON(json: any): LaunchpadContentDigitalBusinessCardResponse {
    return LaunchpadContentDigitalBusinessCardResponseFromJSONTyped(json, false);
}

export function LaunchpadContentDigitalBusinessCardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchpadContentDigitalBusinessCardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'launchpad_id': json['launchpad_id'] == null ? undefined : json['launchpad_id'],
        'button_id': json['button_id'] == null ? undefined : json['button_id'],
        'digital_business_card_id': json['digital_business_card_id'] == null ? undefined : json['digital_business_card_id'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'type': json['type'] == null ? undefined : LaunchpadButtonTypeEnumFromJSON(json['type']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'is_sample': json['is_sample'] == null ? undefined : json['is_sample'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function LaunchpadContentDigitalBusinessCardResponseToJSON(json: any): LaunchpadContentDigitalBusinessCardResponse {
    return LaunchpadContentDigitalBusinessCardResponseToJSONTyped(json, false);
}

export function LaunchpadContentDigitalBusinessCardResponseToJSONTyped(value?: LaunchpadContentDigitalBusinessCardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'launchpad_id': value['launchpad_id'],
        'button_id': value['button_id'],
        'digital_business_card_id': value['digital_business_card_id'],
        'sort_order': value['sort_order'],
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'is_pinned': value['is_pinned'],
        'type': LaunchpadButtonTypeEnumToJSON(value['type']),
        'parent': value['parent'],
        'is_sample': value['is_sample'],
        'title': value['title'],
    };
}

