/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Specifies how to query the next set of results.
 * @export
 * @interface MicrositePagination
 */
export interface MicrositePagination {
    /**
     * A hyperlink to the next set of results.
     * @type {string}
     * @memberof MicrositePagination
     */
    next?: string;
    /**
     * The identifier of where to begin searching for the next set of results.
     * @type {string}
     * @memberof MicrositePagination
     */
    search_after?: string;
    /**
     * The number of results returned from this query.
     * @type {number}
     * @memberof MicrositePagination
     */
    size?: number;
}

/**
 * Check if a given object implements the MicrositePagination interface.
 */
export function instanceOfMicrositePagination(value: object): value is MicrositePagination {
    return true;
}

export function MicrositePaginationFromJSON(json: any): MicrositePagination {
    return MicrositePaginationFromJSONTyped(json, false);
}

export function MicrositePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MicrositePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'next': json['next'] == null ? undefined : json['next'],
        'search_after': json['search_after'] == null ? undefined : json['search_after'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function MicrositePaginationToJSON(json: any): MicrositePagination {
    return MicrositePaginationToJSONTyped(json, false);
}

export function MicrositePaginationToJSONTyped(value?: MicrositePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next': value['next'],
        'search_after': value['search_after'],
        'size': value['size'],
    };
}

