/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MobileOS } from './MobileOS';
import {
    MobileOSFromJSON,
    MobileOSFromJSONTyped,
    MobileOSToJSON,
    MobileOSToJSONTyped,
} from './MobileOS';

/**
 * Deep Linking object
 * @export
 * @interface MinimalDeeplinkApp
 */
export interface MinimalDeeplinkApp {
    /**
     * 
     * @type {string}
     * @memberof MinimalDeeplinkApp
     */
    guid?: string;
    /**
     * 
     * @type {MobileOS}
     * @memberof MinimalDeeplinkApp
     */
    os?: MobileOS;
}



/**
 * Check if a given object implements the MinimalDeeplinkApp interface.
 */
export function instanceOfMinimalDeeplinkApp(value: object): value is MinimalDeeplinkApp {
    return true;
}

export function MinimalDeeplinkAppFromJSON(json: any): MinimalDeeplinkApp {
    return MinimalDeeplinkAppFromJSONTyped(json, false);
}

export function MinimalDeeplinkAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimalDeeplinkApp {
    if (json == null) {
        return json;
    }
    return {
        
        'guid': json['guid'] == null ? undefined : json['guid'],
        'os': json['os'] == null ? undefined : MobileOSFromJSON(json['os']),
    };
}

export function MinimalDeeplinkAppToJSON(json: any): MinimalDeeplinkApp {
    return MinimalDeeplinkAppToJSONTyped(json, false);
}

export function MinimalDeeplinkAppToJSONTyped(value?: MinimalDeeplinkApp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guid': value['guid'],
        'os': MobileOSToJSON(value['os']),
    };
}

