/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGUID
 */
export interface OrganizationGUID {
    /**
     * 
     * @type {string}
     * @memberof OrganizationGUID
     */
    organization_guid?: string;
}

/**
 * Check if a given object implements the OrganizationGUID interface.
 */
export function instanceOfOrganizationGUID(value: object): value is OrganizationGUID {
    return true;
}

export function OrganizationGUIDFromJSON(json: any): OrganizationGUID {
    return OrganizationGUIDFromJSONTyped(json, false);
}

export function OrganizationGUIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGUID {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_guid': json['organization_guid'] == null ? undefined : json['organization_guid'],
    };
}

export function OrganizationGUIDToJSON(json: any): OrganizationGUID {
    return OrganizationGUIDToJSONTyped(json, false);
}

export function OrganizationGUIDToJSONTyped(value?: OrganizationGUID | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_guid': value['organization_guid'],
    };
}

