/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The object representing an Org Domain Verification record
 * @export
 * @interface OrgDomainVerification
 */
export interface OrgDomainVerification {
    /**
     * UUID for the Org Domain Verification Record
     * @type {string}
     * @memberof OrgDomainVerification
     */
    uuid?: string;
    /**
     * Org GUID which the admin user belongs to, and is requesting to create a controlled domain
     * @type {string}
     * @memberof OrgDomainVerification
     */
    org_guid?: string;
    /**
     * Domain which the admin user is requesting to create an org controlled domain
     * @type {string}
     * @memberof OrgDomainVerification
     */
    domain?: string;
    /**
     * Login of the admin user requesting to create an org controlled domain
     * @type {string}
     * @memberof OrgDomainVerification
     */
    login?: string;
    /**
     * Email of the admin user which the org domain verification email is sent
     * @type {string}
     * @memberof OrgDomainVerification
     */
    email?: string;
}

/**
 * Check if a given object implements the OrgDomainVerification interface.
 */
export function instanceOfOrgDomainVerification(value: object): value is OrgDomainVerification {
    return true;
}

export function OrgDomainVerificationFromJSON(json: any): OrgDomainVerification {
    return OrgDomainVerificationFromJSONTyped(json, false);
}

export function OrgDomainVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgDomainVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'org_guid': json['org_guid'] == null ? undefined : json['org_guid'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'login': json['login'] == null ? undefined : json['login'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function OrgDomainVerificationToJSON(json: any): OrgDomainVerification {
    return OrgDomainVerificationToJSONTyped(json, false);
}

export function OrgDomainVerificationToJSONTyped(value?: OrgDomainVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'org_guid': value['org_guid'],
        'domain': value['domain'],
        'login': value['login'],
        'email': value['email'],
    };
}

