/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgDomainStatus } from './OrgDomainStatus';
import {
    OrgDomainStatusFromJSON,
    OrgDomainStatusFromJSONTyped,
    OrgDomainStatusToJSON,
    OrgDomainStatusToJSONTyped,
} from './OrgDomainStatus';

/**
 * 
 * @export
 * @interface OrgDomainsStatus
 */
export interface OrgDomainsStatus {
    /**
     * 
     * @type {Array<OrgDomainStatus>}
     * @memberof OrgDomainsStatus
     */
    org_domains_status?: Array<OrgDomainStatus>;
}

/**
 * Check if a given object implements the OrgDomainsStatus interface.
 */
export function instanceOfOrgDomainsStatus(value: object): value is OrgDomainsStatus {
    return true;
}

export function OrgDomainsStatusFromJSON(json: any): OrgDomainsStatus {
    return OrgDomainsStatusFromJSONTyped(json, false);
}

export function OrgDomainsStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgDomainsStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'org_domains_status': json['org_domains_status'] == null ? undefined : ((json['org_domains_status'] as Array<any>).map(OrgDomainStatusFromJSON)),
    };
}

export function OrgDomainsStatusToJSON(json: any): OrgDomainsStatus {
    return OrgDomainsStatusToJSONTyped(json, false);
}

export function OrgDomainsStatusToJSONTyped(value?: OrgDomainsStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_domains_status': value['org_domains_status'] == null ? undefined : ((value['org_domains_status'] as Array<any>).map(OrgDomainStatusToJSON)),
    };
}

