/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgTierHistory
 */
export interface OrgTierHistory {
    /**
     * 
     * @type {string}
     * @memberof OrgTierHistory
     */
    org_guid: string;
    /**
     * 
     * @type {string}
     * @memberof OrgTierHistory
     */
    status: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof OrgTierHistory
     */
    created: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof OrgTierHistory
     */
    modified: string;
    /**
     * 
     * @type {string}
     * @memberof OrgTierHistory
     */
    tier_name: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof OrgTierHistory
     */
    tier_change_date: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof OrgTierHistory
     */
    activated: string;
    /**
     * ISO timestamp
     * @type {string}
     * @memberof OrgTierHistory
     */
    deactivated: string;
}

/**
 * Check if a given object implements the OrgTierHistory interface.
 */
export function instanceOfOrgTierHistory(value: object): value is OrgTierHistory {
    if (!('org_guid' in value) || value['org_guid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('tier_name' in value) || value['tier_name'] === undefined) return false;
    if (!('tier_change_date' in value) || value['tier_change_date'] === undefined) return false;
    if (!('activated' in value) || value['activated'] === undefined) return false;
    if (!('deactivated' in value) || value['deactivated'] === undefined) return false;
    return true;
}

export function OrgTierHistoryFromJSON(json: any): OrgTierHistory {
    return OrgTierHistoryFromJSONTyped(json, false);
}

export function OrgTierHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgTierHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'org_guid': json['org_guid'],
        'status': json['status'],
        'created': json['created'],
        'modified': json['modified'],
        'tier_name': json['tier_name'],
        'tier_change_date': json['tier_change_date'],
        'activated': json['activated'],
        'deactivated': json['deactivated'],
    };
}

export function OrgTierHistoryToJSON(json: any): OrgTierHistory {
    return OrgTierHistoryToJSONTyped(json, false);
}

export function OrgTierHistoryToJSONTyped(value?: OrgTierHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_guid': value['org_guid'],
        'status': value['status'],
        'created': value['created'],
        'modified': value['modified'],
        'tier_name': value['tier_name'],
        'tier_change_date': value['tier_change_date'],
        'activated': value['activated'],
        'deactivated': value['deactivated'],
    };
}

