/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayPalTokenRequest
 */
export interface PayPalTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof PayPalTokenRequest
     */
    org_guid?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPalTokenRequest
     */
    tier_name?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPalTokenRequest
     */
    billing_period?: string;
}

/**
 * Check if a given object implements the PayPalTokenRequest interface.
 */
export function instanceOfPayPalTokenRequest(value: object): value is PayPalTokenRequest {
    return true;
}

export function PayPalTokenRequestFromJSON(json: any): PayPalTokenRequest {
    return PayPalTokenRequestFromJSONTyped(json, false);
}

export function PayPalTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPalTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'org_guid': json['org_guid'] == null ? undefined : json['org_guid'],
        'tier_name': json['tier_name'] == null ? undefined : json['tier_name'],
        'billing_period': json['billing_period'] == null ? undefined : json['billing_period'],
    };
}

export function PayPalTokenRequestToJSON(json: any): PayPalTokenRequest {
    return PayPalTokenRequestToJSONTyped(json, false);
}

export function PayPalTokenRequestToJSONTyped(value?: PayPalTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_guid': value['org_guid'],
        'tier_name': value['tier_name'],
        'billing_period': value['billing_period'],
    };
}

