/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicSSOUser
 */
export interface PublicSSOUser {
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    guid: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    organization_guid: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    sso_username: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    login: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicSSOUser
     */
    is_active: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    identity_provider: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    modified: string;
    /**
     * 
     * @type {string}
     * @memberof PublicSSOUser
     */
    deactivated: string;
}

/**
 * Check if a given object implements the PublicSSOUser interface.
 */
export function instanceOfPublicSSOUser(value: object): value is PublicSSOUser {
    if (!('guid' in value) || value['guid'] === undefined) return false;
    if (!('organization_guid' in value) || value['organization_guid'] === undefined) return false;
    if (!('sso_username' in value) || value['sso_username'] === undefined) return false;
    if (!('login' in value) || value['login'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    if (!('identity_provider' in value) || value['identity_provider'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('deactivated' in value) || value['deactivated'] === undefined) return false;
    return true;
}

export function PublicSSOUserFromJSON(json: any): PublicSSOUser {
    return PublicSSOUserFromJSONTyped(json, false);
}

export function PublicSSOUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSSOUser {
    if (json == null) {
        return json;
    }
    return {
        
        'guid': json['guid'],
        'organization_guid': json['organization_guid'],
        'sso_username': json['sso_username'],
        'login': json['login'],
        'is_active': json['is_active'],
        'identity_provider': json['identity_provider'],
        'created': json['created'],
        'modified': json['modified'],
        'deactivated': json['deactivated'],
    };
}

export function PublicSSOUserToJSON(json: any): PublicSSOUser {
    return PublicSSOUserToJSONTyped(json, false);
}

export function PublicSSOUserToJSONTyped(value?: PublicSSOUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guid': value['guid'],
        'organization_guid': value['organization_guid'],
        'sso_username': value['sso_username'],
        'login': value['login'],
        'is_active': value['is_active'],
        'identity_provider': value['identity_provider'],
        'created': value['created'],
        'modified': value['modified'],
        'deactivated': value['deactivated'],
    };
}

