/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicImageURL
 */
export interface PublicImageURL {
    /**
     * 
     * @type {string}
     * @memberof PublicImageURL
     */
    public_image_url?: string;
}

/**
 * Check if a given object implements the PublicImageURL interface.
 */
export function instanceOfPublicImageURL(value: object): value is PublicImageURL {
    return true;
}

export function PublicImageURLFromJSON(json: any): PublicImageURL {
    return PublicImageURLFromJSONTyped(json, false);
}

export function PublicImageURLFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicImageURL {
    if (json == null) {
        return json;
    }
    return {
        
        'public_image_url': json['public_image_url'] == null ? undefined : json['public_image_url'],
    };
}

export function PublicImageURLToJSON(json: any): PublicImageURL {
    return PublicImageURLToJSONTyped(json, false);
}

export function PublicImageURLToJSONTyped(value?: PublicImageURL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_image_url': value['public_image_url'],
    };
}

