/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOAuthUser
 */
export interface PublicOAuthUser {
    /**
     * 
     * @type {string}
     * @memberof PublicOAuthUser
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOAuthUser
     */
    access_token?: string;
}

/**
 * Check if a given object implements the PublicOAuthUser interface.
 */
export function instanceOfPublicOAuthUser(value: object): value is PublicOAuthUser {
    return true;
}

export function PublicOAuthUserFromJSON(json: any): PublicOAuthUser {
    return PublicOAuthUserFromJSONTyped(json, false);
}

export function PublicOAuthUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOAuthUser {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'] == null ? undefined : json['login'],
        'access_token': json['Access_Token'] == null ? undefined : json['Access_Token'],
    };
}

export function PublicOAuthUserToJSON(json: any): PublicOAuthUser {
    return PublicOAuthUserToJSONTyped(json, false);
}

export function PublicOAuthUserToJSONTyped(value?: PublicOAuthUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'Access_Token': value['access_token'],
    };
}

