/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A phone number stored in a QR code
 * @export
 * @interface QRCodePhoneNumber
 */
export interface QRCodePhoneNumber {
    /**
     * The recipient's phone number
     * @type {string}
     * @memberof QRCodePhoneNumber
     */
    phone_number?: string;
}

/**
 * Check if a given object implements the QRCodePhoneNumber interface.
 */
export function instanceOfQRCodePhoneNumber(value: object): value is QRCodePhoneNumber {
    return true;
}

export function QRCodePhoneNumberFromJSON(json: any): QRCodePhoneNumber {
    return QRCodePhoneNumberFromJSONTyped(json, false);
}

export function QRCodePhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodePhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
    };
}

export function QRCodePhoneNumberToJSON(json: any): QRCodePhoneNumber {
    return QRCodePhoneNumberToJSONTyped(json, false);
}

export function QRCodePhoneNumberToJSONTyped(value?: QRCodePhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone_number': value['phone_number'],
    };
}

