/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
    TextToJSONTyped,
} from './Text';

/**
 * The text to be inserted into the QR code's frame
 * @export
 * @interface QRCodeFrameRequestText
 */
export interface QRCodeFrameRequestText {
    /**
     * 
     * @type {Text}
     * @memberof QRCodeFrameRequestText
     */
    primary?: Text;
    /**
     * 
     * @type {Text}
     * @memberof QRCodeFrameRequestText
     */
    secondary?: Text;
}

/**
 * Check if a given object implements the QRCodeFrameRequestText interface.
 */
export function instanceOfQRCodeFrameRequestText(value: object): value is QRCodeFrameRequestText {
    return true;
}

export function QRCodeFrameRequestTextFromJSON(json: any): QRCodeFrameRequestText {
    return QRCodeFrameRequestTextFromJSONTyped(json, false);
}

export function QRCodeFrameRequestTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeFrameRequestText {
    if (json == null) {
        return json;
    }
    return {
        
        'primary': json['primary'] == null ? undefined : TextFromJSON(json['primary']),
        'secondary': json['secondary'] == null ? undefined : TextFromJSON(json['secondary']),
    };
}

export function QRCodeFrameRequestTextToJSON(json: any): QRCodeFrameRequestText {
    return QRCodeFrameRequestTextToJSONTyped(json, false);
}

export function QRCodeFrameRequestTextToJSONTyped(value?: QRCodeFrameRequestText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary': TextToJSON(value['primary']),
        'secondary': TextToJSON(value['secondary']),
    };
}

