/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A vertual card, usually business card, stored in a QR code
 * @export
 * @interface QRCodeVirtualCard
 */
export interface QRCodeVirtualCard {
    /**
     * The card owner's first name
     * @type {string}
     * @memberof QRCodeVirtualCard
     */
    first_name?: string;
    /**
     * The card owner's last name
     * @type {string}
     * @memberof QRCodeVirtualCard
     */
    last_name?: string;
    /**
     * A list of the card owner's phone numbers
     * @type {Array<string>}
     * @memberof QRCodeVirtualCard
     */
    phone_numbers?: Array<string>;
}

/**
 * Check if a given object implements the QRCodeVirtualCard interface.
 */
export function instanceOfQRCodeVirtualCard(value: object): value is QRCodeVirtualCard {
    return true;
}

export function QRCodeVirtualCardFromJSON(json: any): QRCodeVirtualCard {
    return QRCodeVirtualCardFromJSONTyped(json, false);
}

export function QRCodeVirtualCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeVirtualCard {
    if (json == null) {
        return json;
    }
    return {
        
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'phone_numbers': json['phone_numbers'] == null ? undefined : json['phone_numbers'],
    };
}

export function QRCodeVirtualCardToJSON(json: any): QRCodeVirtualCard {
    return QRCodeVirtualCardToJSONTyped(json, false);
}

export function QRCodeVirtualCardToJSONTyped(value?: QRCodeVirtualCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'phone_numbers': value['phone_numbers'],
    };
}

