/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QRCodeTemplate } from './QRCodeTemplate';
import {
    QRCodeTemplateFromJSON,
    QRCodeTemplateFromJSONTyped,
    QRCodeTemplateToJSON,
    QRCodeTemplateToJSONTyped,
} from './QRCodeTemplate';

/**
 * A QR Code Templates response
 * @export
 * @interface QRCodeTemplatesResponse
 */
export interface QRCodeTemplatesResponse {
    /**
     * A list of qr code templates
     * @type {Array<QRCodeTemplate>}
     * @memberof QRCodeTemplatesResponse
     */
    qr_code_templates?: Array<QRCodeTemplate>;
}

/**
 * Check if a given object implements the QRCodeTemplatesResponse interface.
 */
export function instanceOfQRCodeTemplatesResponse(value: object): value is QRCodeTemplatesResponse {
    return true;
}

export function QRCodeTemplatesResponseFromJSON(json: any): QRCodeTemplatesResponse {
    return QRCodeTemplatesResponseFromJSONTyped(json, false);
}

export function QRCodeTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeTemplatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qr_code_templates': json['qr_code_templates'] == null ? undefined : ((json['qr_code_templates'] as Array<any>).map(QRCodeTemplateFromJSON)),
    };
}

export function QRCodeTemplatesResponseToJSON(json: any): QRCodeTemplatesResponse {
    return QRCodeTemplatesResponseToJSONTyped(json, false);
}

export function QRCodeTemplatesResponseToJSONTyped(value?: QRCodeTemplatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qr_code_templates': value['qr_code_templates'] == null ? undefined : ((value['qr_code_templates'] as Array<any>).map(QRCodeTemplateToJSON)),
    };
}

