/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A preconfigured email message stored in a QR code
 * @export
 * @interface QRCodeEmail
 */
export interface QRCodeEmail {
    /**
     * The recipient's email address
     * @type {string}
     * @memberof QRCodeEmail
     */
    to?: string;
    /**
     * The sender's email address
     * @type {string}
     * @memberof QRCodeEmail
     */
    from?: string;
    /**
     * Email addresses to be CC'd
     * @type {string}
     * @memberof QRCodeEmail
     */
    cc?: string;
    /**
     * The email's subject
     * @type {string}
     * @memberof QRCodeEmail
     */
    subject?: string;
    /**
     * The email's body
     * @type {string}
     * @memberof QRCodeEmail
     */
    body?: string;
}

/**
 * Check if a given object implements the QRCodeEmail interface.
 */
export function instanceOfQRCodeEmail(value: object): value is QRCodeEmail {
    return true;
}

export function QRCodeEmailFromJSON(json: any): QRCodeEmail {
    return QRCodeEmailFromJSONTyped(json, false);
}

export function QRCodeEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'from': json['from'] == null ? undefined : json['from'],
        'cc': json['cc'] == null ? undefined : json['cc'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function QRCodeEmailToJSON(json: any): QRCodeEmail {
    return QRCodeEmailToJSONTyped(json, false);
}

export function QRCodeEmailToJSONTyped(value?: QRCodeEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'from': value['from'],
        'cc': value['cc'],
        'subject': value['subject'],
        'body': value['body'],
    };
}

