/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QRCodeFrameType } from './QRCodeFrameType';
import {
    QRCodeFrameTypeFromJSON,
    QRCodeFrameTypeFromJSONTyped,
    QRCodeFrameTypeToJSON,
    QRCodeFrameTypeToJSONTyped,
} from './QRCodeFrameType';
import type { QRCodeFrameRequestColors } from './QRCodeFrameRequestColors';
import {
    QRCodeFrameRequestColorsFromJSON,
    QRCodeFrameRequestColorsFromJSONTyped,
    QRCodeFrameRequestColorsToJSON,
    QRCodeFrameRequestColorsToJSONTyped,
} from './QRCodeFrameRequestColors';
import type { QRCodeFrameRequestText } from './QRCodeFrameRequestText';
import {
    QRCodeFrameRequestTextFromJSON,
    QRCodeFrameRequestTextFromJSONTyped,
    QRCodeFrameRequestTextToJSON,
    QRCodeFrameRequestTextToJSONTyped,
} from './QRCodeFrameRequestText';

/**
 * 
 * @export
 * @interface QRCodeFrameRequest
 */
export interface QRCodeFrameRequest {
    /**
     * 
     * @type {QRCodeFrameType}
     * @memberof QRCodeFrameRequest
     */
    id: QRCodeFrameType;
    /**
     * 
     * @type {QRCodeFrameRequestColors}
     * @memberof QRCodeFrameRequest
     */
    colors?: QRCodeFrameRequestColors;
    /**
     * 
     * @type {QRCodeFrameRequestText}
     * @memberof QRCodeFrameRequest
     */
    text?: QRCodeFrameRequestText;
}



/**
 * Check if a given object implements the QRCodeFrameRequest interface.
 */
export function instanceOfQRCodeFrameRequest(value: object): value is QRCodeFrameRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function QRCodeFrameRequestFromJSON(json: any): QRCodeFrameRequest {
    return QRCodeFrameRequestFromJSONTyped(json, false);
}

export function QRCodeFrameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeFrameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': QRCodeFrameTypeFromJSON(json['id']),
        'colors': json['colors'] == null ? undefined : QRCodeFrameRequestColorsFromJSON(json['colors']),
        'text': json['text'] == null ? undefined : QRCodeFrameRequestTextFromJSON(json['text']),
    };
}

export function QRCodeFrameRequestToJSON(json: any): QRCodeFrameRequest {
    return QRCodeFrameRequestToJSONTyped(json, false);
}

export function QRCodeFrameRequestToJSONTyped(value?: QRCodeFrameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': QRCodeFrameTypeToJSON(value['id']),
        'colors': QRCodeFrameRequestColorsToJSON(value['colors']),
        'text': QRCodeFrameRequestTextToJSON(value['text']),
    };
}

