/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QRCodeGradient } from './QRCodeGradient';
import {
    QRCodeGradientFromJSON,
    QRCodeGradientFromJSONTyped,
    QRCodeGradientToJSON,
    QRCodeGradientToJSONTyped,
} from './QRCodeGradient';
import type { QRCodeDotPatternType } from './QRCodeDotPatternType';
import {
    QRCodeDotPatternTypeFromJSON,
    QRCodeDotPatternTypeFromJSONTyped,
    QRCodeDotPatternTypeToJSON,
    QRCodeDotPatternTypeToJSONTyped,
} from './QRCodeDotPatternType';
import type { QRCodeCorners } from './QRCodeCorners';
import {
    QRCodeCornersFromJSON,
    QRCodeCornersFromJSONTyped,
    QRCodeCornersToJSON,
    QRCodeCornersToJSONTyped,
} from './QRCodeCorners';
import type { QRCodeFrameRequest } from './QRCodeFrameRequest';
import {
    QRCodeFrameRequestFromJSON,
    QRCodeFrameRequestFromJSONTyped,
    QRCodeFrameRequestToJSON,
    QRCodeFrameRequestToJSONTyped,
} from './QRCodeFrameRequest';
import type { QRCodeSpecSettings } from './QRCodeSpecSettings';
import {
    QRCodeSpecSettingsFromJSON,
    QRCodeSpecSettingsFromJSONTyped,
    QRCodeSpecSettingsToJSON,
    QRCodeSpecSettingsToJSONTyped,
} from './QRCodeSpecSettings';
import type { QRCodeBranding } from './QRCodeBranding';
import {
    QRCodeBrandingFromJSON,
    QRCodeBrandingFromJSONTyped,
    QRCodeBrandingToJSON,
    QRCodeBrandingToJSONTyped,
} from './QRCodeBranding';
import type { QRCodeLogo } from './QRCodeLogo';
import {
    QRCodeLogoFromJSON,
    QRCodeLogoFromJSONTyped,
    QRCodeLogoToJSON,
    QRCodeLogoToJSONTyped,
} from './QRCodeLogo';
import type { QRCodeText } from './QRCodeText';
import {
    QRCodeTextFromJSON,
    QRCodeTextFromJSONTyped,
    QRCodeTextToJSON,
    QRCodeTextToJSONTyped,
} from './QRCodeText';

/**
 * Options for customizing a QR Code's appearance
 * @export
 * @interface QRCodeCustomizations
 */
export interface QRCodeCustomizations {
    /**
     * The QR code's background color in hex code format with values for alpha channel
     * @type {string}
     * @memberof QRCodeCustomizations
     */
    background_color?: string;
    /**
     * The QR code's dot pattern color in hex code format
     * @type {string}
     * @memberof QRCodeCustomizations
     */
    dot_pattern_color?: string;
    /**
     * 
     * @type {QRCodeDotPatternType}
     * @memberof QRCodeCustomizations
     */
    dot_pattern_type?: QRCodeDotPatternType;
    /**
     * 
     * @type {QRCodeCorners}
     * @memberof QRCodeCustomizations
     */
    corners?: QRCodeCorners;
    /**
     * 
     * @type {QRCodeGradient}
     * @memberof QRCodeCustomizations
     */
    gradient?: QRCodeGradient;
    /**
     * 
     * @type {QRCodeGradient}
     * @memberof QRCodeCustomizations
     */
    background_gradient?: QRCodeGradient;
    /**
     * 
     * @type {QRCodeLogo}
     * @memberof QRCodeCustomizations
     */
    logo?: QRCodeLogo;
    /**
     * 
     * @type {QRCodeFrameRequest}
     * @memberof QRCodeCustomizations
     */
    frame?: QRCodeFrameRequest;
    /**
     * 
     * @type {QRCodeText}
     * @memberof QRCodeCustomizations
     */
    text?: QRCodeText;
    /**
     * 
     * @type {QRCodeBranding}
     * @memberof QRCodeCustomizations
     */
    branding?: QRCodeBranding;
    /**
     * 
     * @type {QRCodeSpecSettings}
     * @memberof QRCodeCustomizations
     */
    spec_settings?: QRCodeSpecSettings;
}



/**
 * Check if a given object implements the QRCodeCustomizations interface.
 */
export function instanceOfQRCodeCustomizations(value: object): value is QRCodeCustomizations {
    return true;
}

export function QRCodeCustomizationsFromJSON(json: any): QRCodeCustomizations {
    return QRCodeCustomizationsFromJSONTyped(json, false);
}

export function QRCodeCustomizationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeCustomizations {
    if (json == null) {
        return json;
    }
    return {
        
        'background_color': json['background_color'] == null ? undefined : json['background_color'],
        'dot_pattern_color': json['dot_pattern_color'] == null ? undefined : json['dot_pattern_color'],
        'dot_pattern_type': json['dot_pattern_type'] == null ? undefined : QRCodeDotPatternTypeFromJSON(json['dot_pattern_type']),
        'corners': json['corners'] == null ? undefined : QRCodeCornersFromJSON(json['corners']),
        'gradient': json['gradient'] == null ? undefined : QRCodeGradientFromJSON(json['gradient']),
        'background_gradient': json['background_gradient'] == null ? undefined : QRCodeGradientFromJSON(json['background_gradient']),
        'logo': json['logo'] == null ? undefined : QRCodeLogoFromJSON(json['logo']),
        'frame': json['frame'] == null ? undefined : QRCodeFrameRequestFromJSON(json['frame']),
        'text': json['text'] == null ? undefined : QRCodeTextFromJSON(json['text']),
        'branding': json['branding'] == null ? undefined : QRCodeBrandingFromJSON(json['branding']),
        'spec_settings': json['spec_settings'] == null ? undefined : QRCodeSpecSettingsFromJSON(json['spec_settings']),
    };
}

export function QRCodeCustomizationsToJSON(json: any): QRCodeCustomizations {
    return QRCodeCustomizationsToJSONTyped(json, false);
}

export function QRCodeCustomizationsToJSONTyped(value?: QRCodeCustomizations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'background_color': value['background_color'],
        'dot_pattern_color': value['dot_pattern_color'],
        'dot_pattern_type': QRCodeDotPatternTypeToJSON(value['dot_pattern_type']),
        'corners': QRCodeCornersToJSON(value['corners']),
        'gradient': QRCodeGradientToJSON(value['gradient']),
        'background_gradient': QRCodeGradientToJSON(value['background_gradient']),
        'logo': QRCodeLogoToJSON(value['logo']),
        'frame': QRCodeFrameRequestToJSON(value['frame']),
        'text': QRCodeTextToJSON(value['text']),
        'branding': QRCodeBrandingToJSON(value['branding']),
        'spec_settings': QRCodeSpecSettingsToJSON(value['spec_settings']),
    };
}

