/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object of named colors denoting which color should go to which area of the frame
 * @export
 * @interface QRCodeFrameRequestColors
 */
export interface QRCodeFrameRequestColors {
    /**
     * The primary color of the frame in hex code format
     * @type {string}
     * @memberof QRCodeFrameRequestColors
     */
    primary?: string;
    /**
     * The secondary color of the frame in hex code format
     * @type {string}
     * @memberof QRCodeFrameRequestColors
     */
    secondary?: string;
    /**
     * The background color of the frame in hex code format
     * @type {string}
     * @memberof QRCodeFrameRequestColors
     */
    background?: string;
}

/**
 * Check if a given object implements the QRCodeFrameRequestColors interface.
 */
export function instanceOfQRCodeFrameRequestColors(value: object): value is QRCodeFrameRequestColors {
    return true;
}

export function QRCodeFrameRequestColorsFromJSON(json: any): QRCodeFrameRequestColors {
    return QRCodeFrameRequestColorsFromJSONTyped(json, false);
}

export function QRCodeFrameRequestColorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeFrameRequestColors {
    if (json == null) {
        return json;
    }
    return {
        
        'primary': json['primary'] == null ? undefined : json['primary'],
        'secondary': json['secondary'] == null ? undefined : json['secondary'],
        'background': json['background'] == null ? undefined : json['background'],
    };
}

export function QRCodeFrameRequestColorsToJSON(json: any): QRCodeFrameRequestColors {
    return QRCodeFrameRequestColorsToJSONTyped(json, false);
}

export function QRCodeFrameRequestColorsToJSONTyped(value?: QRCodeFrameRequestColors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary': value['primary'],
        'secondary': value['secondary'],
        'background': value['background'],
    };
}

