/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to redirect a QRCode
 * @export
 * @interface RedirectQRCodeRequest
 */
export interface RedirectQRCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof RedirectQRCodeRequest
     */
    long_url: string;
}

/**
 * Check if a given object implements the RedirectQRCodeRequest interface.
 */
export function instanceOfRedirectQRCodeRequest(value: object): value is RedirectQRCodeRequest {
    if (!('long_url' in value) || value['long_url'] === undefined) return false;
    return true;
}

export function RedirectQRCodeRequestFromJSON(json: any): RedirectQRCodeRequest {
    return RedirectQRCodeRequestFromJSONTyped(json, false);
}

export function RedirectQRCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectQRCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'long_url': json['long_url'],
    };
}

export function RedirectQRCodeRequestToJSON(json: any): RedirectQRCodeRequest {
    return RedirectQRCodeRequestToJSONTyped(json, false);
}

export function RedirectQRCodeRequestToJSONTyped(value?: RedirectQRCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'long_url': value['long_url'],
    };
}

