/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ReportType {
    links_and_codes = 'links_and_codes',
    pages = 'pages'
}


export function instanceOfReportType(value: any): boolean {
    for (const key in ReportType) {
        if (Object.prototype.hasOwnProperty.call(ReportType, key)) {
            if (ReportType[key as keyof typeof ReportType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReportTypeFromJSON(json: any): ReportType {
    return ReportTypeFromJSONTyped(json, false);
}

export function ReportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportType {
    return json as ReportType;
}

export function ReportTypeToJSON(value?: ReportType | null): any {
    return value as any;
}

export function ReportTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReportType {
    return value as ReportType;
}

