/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScanMetric } from './ScanMetric';
import {
    ScanMetricFromJSON,
    ScanMetricFromJSONTyped,
    ScanMetricToJSON,
    ScanMetricToJSONTyped,
} from './ScanMetric';

/**
 * 
 * @export
 * @interface ScanMetrics
 */
export interface ScanMetrics {
    /**
     * 
     * @type {string}
     * @memberof ScanMetrics
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof ScanMetrics
     */
    units?: number;
    /**
     * 
     * @type {string}
     * @memberof ScanMetrics
     */
    facet?: ScanMetricsFacetEnum;
    /**
     * 
     * @type {string}
     * @memberof ScanMetrics
     */
    unit_reference?: string;
    /**
     * 
     * @type {Array<ScanMetric>}
     * @memberof ScanMetrics
     */
    metrics?: Array<ScanMetric>;
}

/**
* @export
* @enum {string}
*/
export enum ScanMetricsFacetEnum {
    countries = 'countries',
    cities = 'cities',
    device_os = 'device_os',
    browsers = 'browsers'
}


/**
 * Check if a given object implements the ScanMetrics interface.
 */
export function instanceOfScanMetrics(value: object): value is ScanMetrics {
    return true;
}

export function ScanMetricsFromJSON(json: any): ScanMetrics {
    return ScanMetricsFromJSONTyped(json, false);
}

export function ScanMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'unit': json['unit'] == null ? undefined : json['unit'],
        'units': json['units'] == null ? undefined : json['units'],
        'facet': json['facet'] == null ? undefined : json['facet'],
        'unit_reference': json['unit_reference'] == null ? undefined : json['unit_reference'],
        'metrics': json['metrics'] == null ? undefined : ((json['metrics'] as Array<any>).map(ScanMetricFromJSON)),
    };
}

export function ScanMetricsToJSON(json: any): ScanMetrics {
    return ScanMetricsToJSONTyped(json, false);
}

export function ScanMetricsToJSONTyped(value?: ScanMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unit': value['unit'],
        'units': value['units'],
        'facet': value['facet'],
        'unit_reference': value['unit_reference'],
        'metrics': value['metrics'] == null ? undefined : ((value['metrics'] as Array<any>).map(ScanMetricToJSON)),
    };
}

