/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareableReport
 */
export interface ShareableReport {
    /**
     * 
     * @type {string}
     * @memberof ShareableReport
     */
    shareable_report?: string;
    /**
     * 
     * @type {string}
     * @memberof ShareableReport
     */
    bitlink_id?: string;
}

/**
 * Check if a given object implements the ShareableReport interface.
 */
export function instanceOfShareableReport(value: object): value is ShareableReport {
    return true;
}

export function ShareableReportFromJSON(json: any): ShareableReport {
    return ShareableReportFromJSONTyped(json, false);
}

export function ShareableReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareableReport {
    if (json == null) {
        return json;
    }
    return {
        
        'shareable_report': json['shareable_report'] == null ? undefined : json['shareable_report'],
        'bitlink_id': json['bitlink_id'] == null ? undefined : json['bitlink_id'],
    };
}

export function ShareableReportToJSON(json: any): ShareableReport {
    return ShareableReportToJSONTyped(json, false);
}

export function ShareableReportToJSONTyped(value?: ShareableReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shareable_report': value['shareable_report'],
        'bitlink_id': value['bitlink_id'],
    };
}

