/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShopifyBitlinkOrderTotal } from './ShopifyBitlinkOrderTotal';
import {
    ShopifyBitlinkOrderTotalFromJSON,
    ShopifyBitlinkOrderTotalFromJSONTyped,
    ShopifyBitlinkOrderTotalToJSON,
    ShopifyBitlinkOrderTotalToJSONTyped,
} from './ShopifyBitlinkOrderTotal';

/**
 * 
 * @export
 * @interface ShopifyBitlinkOrderMetrics
 */
export interface ShopifyBitlinkOrderMetrics {
    /**
     * ID used to retrieve the next page of results
     * @type {string}
     * @memberof ShopifyBitlinkOrderMetrics
     */
    continuation_id?: string;
    /**
     * 
     * @type {Array<ShopifyBitlinkOrderTotal>}
     * @memberof ShopifyBitlinkOrderMetrics
     */
    bitlink_order_totals?: Array<ShopifyBitlinkOrderTotal>;
}

/**
 * Check if a given object implements the ShopifyBitlinkOrderMetrics interface.
 */
export function instanceOfShopifyBitlinkOrderMetrics(value: object): value is ShopifyBitlinkOrderMetrics {
    return true;
}

export function ShopifyBitlinkOrderMetricsFromJSON(json: any): ShopifyBitlinkOrderMetrics {
    return ShopifyBitlinkOrderMetricsFromJSONTyped(json, false);
}

export function ShopifyBitlinkOrderMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopifyBitlinkOrderMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'continuation_id': json['continuation_id'] == null ? undefined : json['continuation_id'],
        'bitlink_order_totals': json['bitlink_order_totals'] == null ? undefined : ((json['bitlink_order_totals'] as Array<any>).map(ShopifyBitlinkOrderTotalFromJSON)),
    };
}

export function ShopifyBitlinkOrderMetricsToJSON(json: any): ShopifyBitlinkOrderMetrics {
    return ShopifyBitlinkOrderMetricsToJSONTyped(json, false);
}

export function ShopifyBitlinkOrderMetricsToJSONTyped(value?: ShopifyBitlinkOrderMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'continuation_id': value['continuation_id'],
        'bitlink_order_totals': value['bitlink_order_totals'] == null ? undefined : ((value['bitlink_order_totals'] as Array<any>).map(ShopifyBitlinkOrderTotalToJSON)),
    };
}

