/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextBlockAppearanceRequest } from './TextBlockAppearanceRequest';
import {
    TextBlockAppearanceRequestFromJSON,
    TextBlockAppearanceRequestFromJSONTyped,
    TextBlockAppearanceRequestToJSON,
    TextBlockAppearanceRequestToJSONTyped,
} from './TextBlockAppearanceRequest';
import type { SiteContentUnion } from './SiteContentUnion';
import {
    SiteContentUnionFromJSON,
    SiteContentUnionFromJSONTyped,
    SiteContentUnionToJSON,
    SiteContentUnionToJSONTyped,
} from './SiteContentUnion';

/**
 * 
 * @export
 * @interface SiteContentRequest
 */
export interface SiteContentRequest {
    /**
     * 
     * @type {SiteContentUnion}
     * @memberof SiteContentRequest
     */
    content?: SiteContentUnion;
    /**
     * 
     * @type {TextBlockAppearanceRequest}
     * @memberof SiteContentRequest
     */
    appearance?: TextBlockAppearanceRequest;
    /**
     * 
     * @type {string}
     * @memberof SiteContentRequest
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof SiteContentRequest
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SiteContentRequest
     */
    is_active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SiteContentRequest
     */
    is_pinned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SiteContentRequest
     */
    parent?: string;
}

/**
 * Check if a given object implements the SiteContentRequest interface.
 */
export function instanceOfSiteContentRequest(value: object): value is SiteContentRequest {
    return true;
}

export function SiteContentRequestFromJSON(json: any): SiteContentRequest {
    return SiteContentRequestFromJSONTyped(json, false);
}

export function SiteContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : SiteContentUnionFromJSON(json['content']),
        'appearance': json['appearance'] == null ? undefined : TextBlockAppearanceRequestFromJSON(json['appearance']),
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'parent': json['parent'] == null ? undefined : json['parent'],
    };
}

export function SiteContentRequestToJSON(json: any): SiteContentRequest {
    return SiteContentRequestToJSONTyped(json, false);
}

export function SiteContentRequestToJSONTyped(value?: SiteContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': SiteContentUnionToJSON(value['content']),
        'appearance': TextBlockAppearanceRequestToJSON(value['appearance']),
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'is_pinned': value['is_pinned'],
        'parent': value['parent'],
    };
}

