/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Block types that can be created directly (grid and carousel are created as containers)
 * @export
 * @enum {string}
 */
export enum SiteBlockCreateTypeEnum {
    bitlink = 'bitlink',
    social = 'social',
    youtube_video = 'youtubeVideo',
    image = 'image',
    digital_business_card = 'digital_business_card',
    text_block = 'text_block'
}


export function instanceOfSiteBlockCreateTypeEnum(value: any): boolean {
    for (const key in SiteBlockCreateTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(SiteBlockCreateTypeEnum, key)) {
            if (SiteBlockCreateTypeEnum[key as keyof typeof SiteBlockCreateTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SiteBlockCreateTypeEnumFromJSON(json: any): SiteBlockCreateTypeEnum {
    return SiteBlockCreateTypeEnumFromJSONTyped(json, false);
}

export function SiteBlockCreateTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBlockCreateTypeEnum {
    return json as SiteBlockCreateTypeEnum;
}

export function SiteBlockCreateTypeEnumToJSON(value?: SiteBlockCreateTypeEnum | null): any {
    return value as any;
}

export function SiteBlockCreateTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SiteBlockCreateTypeEnum {
    return value as SiteBlockCreateTypeEnum;
}

