/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextBlockAppearanceRequest } from './TextBlockAppearanceRequest';
import {
    TextBlockAppearanceRequestFromJSON,
    TextBlockAppearanceRequestFromJSONTyped,
    TextBlockAppearanceRequestToJSON,
    TextBlockAppearanceRequestToJSONTyped,
} from './TextBlockAppearanceRequest';
import type { SiteContentUnion } from './SiteContentUnion';
import {
    SiteContentUnionFromJSON,
    SiteContentUnionFromJSONTyped,
    SiteContentUnionToJSON,
    SiteContentUnionToJSONTyped,
} from './SiteContentUnion';
import type { SiteBlockCreateTypeEnum } from './SiteBlockCreateTypeEnum';
import {
    SiteBlockCreateTypeEnumFromJSON,
    SiteBlockCreateTypeEnumFromJSONTyped,
    SiteBlockCreateTypeEnumToJSON,
    SiteBlockCreateTypeEnumToJSONTyped,
} from './SiteBlockCreateTypeEnum';

/**
 * 
 * @export
 * @interface SiteBlockCreateRequest
 */
export interface SiteBlockCreateRequest {
    /**
     * 
     * @type {SiteContentUnion}
     * @memberof SiteBlockCreateRequest
     */
    content: SiteContentUnion;
    /**
     * 
     * @type {TextBlockAppearanceRequest}
     * @memberof SiteBlockCreateRequest
     */
    appearance?: TextBlockAppearanceRequest;
    /**
     * 
     * @type {string}
     * @memberof SiteBlockCreateRequest
     */
    schedule_start?: string;
    /**
     * 
     * @type {string}
     * @memberof SiteBlockCreateRequest
     */
    schedule_end?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SiteBlockCreateRequest
     */
    is_active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SiteBlockCreateRequest
     */
    is_pinned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SiteBlockCreateRequest
     */
    parent?: string;
    /**
     * 
     * @type {SiteBlockCreateTypeEnum}
     * @memberof SiteBlockCreateRequest
     */
    type: SiteBlockCreateTypeEnum;
}



/**
 * Check if a given object implements the SiteBlockCreateRequest interface.
 */
export function instanceOfSiteBlockCreateRequest(value: object): value is SiteBlockCreateRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SiteBlockCreateRequestFromJSON(json: any): SiteBlockCreateRequest {
    return SiteBlockCreateRequestFromJSONTyped(json, false);
}

export function SiteBlockCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteBlockCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': SiteContentUnionFromJSON(json['content']),
        'appearance': json['appearance'] == null ? undefined : TextBlockAppearanceRequestFromJSON(json['appearance']),
        'schedule_start': json['schedule_start'] == null ? undefined : json['schedule_start'],
        'schedule_end': json['schedule_end'] == null ? undefined : json['schedule_end'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
        'is_pinned': json['is_pinned'] == null ? undefined : json['is_pinned'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'type': SiteBlockCreateTypeEnumFromJSON(json['type']),
    };
}

export function SiteBlockCreateRequestToJSON(json: any): SiteBlockCreateRequest {
    return SiteBlockCreateRequestToJSONTyped(json, false);
}

export function SiteBlockCreateRequestToJSONTyped(value?: SiteBlockCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': SiteContentUnionToJSON(value['content']),
        'appearance': TextBlockAppearanceRequestToJSON(value['appearance']),
        'schedule_start': value['schedule_start'],
        'schedule_end': value['schedule_end'],
        'is_active': value['is_active'],
        'is_pinned': value['is_pinned'],
        'parent': value['parent'],
        'type': SiteBlockCreateTypeEnumToJSON(value['type']),
    };
}

