/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialContent
 */
export interface SocialContent {
    /**
     * 
     * @type {string}
     * @memberof SocialContent
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialContent
     */
    channel?: string;
}

/**
 * Check if a given object implements the SocialContent interface.
 */
export function instanceOfSocialContent(value: object): value is SocialContent {
    return true;
}

export function SocialContentFromJSON(json: any): SocialContent {
    return SocialContentFromJSONTyped(json, false);
}

export function SocialContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialContent {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'channel': json['channel'] == null ? undefined : json['channel'],
    };
}

export function SocialContentToJSON(json: any): SocialContent {
    return SocialContentToJSONTyped(json, false);
}

export function SocialContentToJSONTyped(value?: SocialContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'channel': value['channel'],
    };
}

