/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EngagementForSort } from './EngagementForSort';
import {
    EngagementForSortFromJSON,
    EngagementForSortFromJSONTyped,
    EngagementForSortToJSON,
    EngagementForSortToJSONTyped,
} from './EngagementForSort';

/**
 * 
 * @export
 * @interface SortedEngagements
 */
export interface SortedEngagements {
    /**
     * 
     * @type {string}
     * @memberof SortedEngagements
     */
    unit_reference?: string;
    /**
     * 
     * @type {string}
     * @memberof SortedEngagements
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof SortedEngagements
     */
    units?: number;
    /**
     * 
     * @type {Array<EngagementForSort>}
     * @memberof SortedEngagements
     */
    sorted_engagements?: Array<EngagementForSort>;
}

/**
 * Check if a given object implements the SortedEngagements interface.
 */
export function instanceOfSortedEngagements(value: object): value is SortedEngagements {
    return true;
}

export function SortedEngagementsFromJSON(json: any): SortedEngagements {
    return SortedEngagementsFromJSONTyped(json, false);
}

export function SortedEngagementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortedEngagements {
    if (json == null) {
        return json;
    }
    return {
        
        'unit_reference': json['unit_reference'] == null ? undefined : json['unit_reference'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'units': json['units'] == null ? undefined : json['units'],
        'sorted_engagements': json['sorted_engagements'] == null ? undefined : ((json['sorted_engagements'] as Array<any>).map(EngagementForSortFromJSON)),
    };
}

export function SortedEngagementsToJSON(json: any): SortedEngagements {
    return SortedEngagementsToJSONTyped(json, false);
}

export function SortedEngagementsToJSONTyped(value?: SortedEngagements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unit_reference': value['unit_reference'],
        'unit': value['unit'],
        'units': value['units'],
        'sorted_engagements': value['sorted_engagements'] == null ? undefined : ((value['sorted_engagements'] as Array<any>).map(EngagementForSortToJSON)),
    };
}

