/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SSOVerifySlug
 */
export interface SSOVerifySlug {
    /**
     * 
     * @type {string}
     * @memberof SSOVerifySlug
     */
    url_slug?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SSOVerifySlug
     */
    available?: boolean;
}

/**
 * Check if a given object implements the SSOVerifySlug interface.
 */
export function instanceOfSSOVerifySlug(value: object): value is SSOVerifySlug {
    return true;
}

export function SSOVerifySlugFromJSON(json: any): SSOVerifySlug {
    return SSOVerifySlugFromJSONTyped(json, false);
}

export function SSOVerifySlugFromJSONTyped(json: any, ignoreDiscriminator: boolean): SSOVerifySlug {
    if (json == null) {
        return json;
    }
    return {
        
        'url_slug': json['url_slug'] == null ? undefined : json['url_slug'],
        'available': json['available'] == null ? undefined : json['available'],
    };
}

export function SSOVerifySlugToJSON(json: any): SSOVerifySlug {
    return SSOVerifySlugToJSONTyped(json, false);
}

export function SSOVerifySlugToJSONTyped(value?: SSOVerifySlug | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url_slug': value['url_slug'],
        'available': value['available'],
    };
}

