/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionDiscount
 */
export interface SubscriptionDiscount {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    billing_period?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    effective_end_date?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    effective_start_date?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    up_to_periods_type?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    product_rate_plan_charge_id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDiscount
     */
    end_date_condition?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionDiscount
     */
    up_to_periods?: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionDiscount
     */
    discount_amount?: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionDiscount
     */
    discount_percentage?: number;
}

/**
 * Check if a given object implements the SubscriptionDiscount interface.
 */
export function instanceOfSubscriptionDiscount(value: object): value is SubscriptionDiscount {
    return true;
}

export function SubscriptionDiscountFromJSON(json: any): SubscriptionDiscount {
    return SubscriptionDiscountFromJSONTyped(json, false);
}

export function SubscriptionDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionDiscount {
    if (json == null) {
        return json;
    }
    return {
        
        'billing_period': json['billing_period'] == null ? undefined : json['billing_period'],
        'effective_end_date': json['effective_end_date'] == null ? undefined : json['effective_end_date'],
        'effective_start_date': json['effective_start_date'] == null ? undefined : json['effective_start_date'],
        'up_to_periods_type': json['up_to_periods_type'] == null ? undefined : json['up_to_periods_type'],
        'product_rate_plan_charge_id': json['product_rate_plan_charge_id'] == null ? undefined : json['product_rate_plan_charge_id'],
        'model': json['model'] == null ? undefined : json['model'],
        'end_date_condition': json['end_date_condition'] == null ? undefined : json['end_date_condition'],
        'up_to_periods': json['up_to_periods'] == null ? undefined : json['up_to_periods'],
        'discount_amount': json['discount_amount'] == null ? undefined : json['discount_amount'],
        'discount_percentage': json['discount_percentage'] == null ? undefined : json['discount_percentage'],
    };
}

export function SubscriptionDiscountToJSON(json: any): SubscriptionDiscount {
    return SubscriptionDiscountToJSONTyped(json, false);
}

export function SubscriptionDiscountToJSONTyped(value?: SubscriptionDiscount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_period': value['billing_period'],
        'effective_end_date': value['effective_end_date'],
        'effective_start_date': value['effective_start_date'],
        'up_to_periods_type': value['up_to_periods_type'],
        'product_rate_plan_charge_id': value['product_rate_plan_charge_id'],
        'model': value['model'],
        'end_date_condition': value['end_date_condition'],
        'up_to_periods': value['up_to_periods'],
        'discount_amount': value['discount_amount'],
        'discount_percentage': value['discount_percentage'],
    };
}

