/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TextBlockAppearanceRequestFontSizeEnum {
    small = 'small',
    medium = 'medium',
    large = 'large',
    extra_large = 'extra_large'
}


export function instanceOfTextBlockAppearanceRequestFontSizeEnum(value: any): boolean {
    for (const key in TextBlockAppearanceRequestFontSizeEnum) {
        if (Object.prototype.hasOwnProperty.call(TextBlockAppearanceRequestFontSizeEnum, key)) {
            if (TextBlockAppearanceRequestFontSizeEnum[key as keyof typeof TextBlockAppearanceRequestFontSizeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TextBlockAppearanceRequestFontSizeEnumFromJSON(json: any): TextBlockAppearanceRequestFontSizeEnum {
    return TextBlockAppearanceRequestFontSizeEnumFromJSONTyped(json, false);
}

export function TextBlockAppearanceRequestFontSizeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextBlockAppearanceRequestFontSizeEnum {
    return json as TextBlockAppearanceRequestFontSizeEnum;
}

export function TextBlockAppearanceRequestFontSizeEnumToJSON(value?: TextBlockAppearanceRequestFontSizeEnum | null): any {
    return value as any;
}

export function TextBlockAppearanceRequestFontSizeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TextBlockAppearanceRequestFontSizeEnum {
    return value as TextBlockAppearanceRequestFontSizeEnum;
}

