/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackRequest
 */
export interface TrackRequest {
    /**
     * 
     * @type {string}
     * @memberof TrackRequest
     */
    event_key: string;
    /**
     * 
     * @type {string}
     * @memberof TrackRequest
     */
    org_guid: string;
}

/**
 * Check if a given object implements the TrackRequest interface.
 */
export function instanceOfTrackRequest(value: object): value is TrackRequest {
    if (!('event_key' in value) || value['event_key'] === undefined) return false;
    if (!('org_guid' in value) || value['org_guid'] === undefined) return false;
    return true;
}

export function TrackRequestFromJSON(json: any): TrackRequest {
    return TrackRequestFromJSONTyped(json, false);
}

export function TrackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event_key': json['event_key'],
        'org_guid': json['org_guid'],
    };
}

export function TrackRequestToJSON(json: any): TrackRequest {
    return TrackRequestToJSONTyped(json, false);
}

export function TrackRequestToJSONTyped(value?: TrackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_key': value['event_key'],
        'org_guid': value['org_guid'],
    };
}

