/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TwoFactorCode
 */
export interface TwoFactorCode {
    /**
     * 
     * @type {string}
     * @memberof TwoFactorCode
     */
    code: string;
}

/**
 * Check if a given object implements the TwoFactorCode interface.
 */
export function instanceOfTwoFactorCode(value: object): value is TwoFactorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function TwoFactorCodeFromJSON(json: any): TwoFactorCode {
    return TwoFactorCodeFromJSONTyped(json, false);
}

export function TwoFactorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwoFactorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function TwoFactorCodeToJSON(json: any): TwoFactorCode {
    return TwoFactorCodeToJSONTyped(json, false);
}

export function TwoFactorCodeToJSONTyped(value?: TwoFactorCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

