/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LaunchpadButtonSortOrder } from './LaunchpadButtonSortOrder';
import {
    LaunchpadButtonSortOrderFromJSON,
    LaunchpadButtonSortOrderFromJSONTyped,
    LaunchpadButtonSortOrderToJSON,
    LaunchpadButtonSortOrderToJSONTyped,
} from './LaunchpadButtonSortOrder';

/**
 * 
 * @export
 * @interface UpdateButtonSortOrder
 */
export interface UpdateButtonSortOrder {
    /**
     * 
     * @type {Array<LaunchpadButtonSortOrder>}
     * @memberof UpdateButtonSortOrder
     */
    buttons?: Array<LaunchpadButtonSortOrder>;
}

/**
 * Check if a given object implements the UpdateButtonSortOrder interface.
 */
export function instanceOfUpdateButtonSortOrder(value: object): value is UpdateButtonSortOrder {
    return true;
}

export function UpdateButtonSortOrderFromJSON(json: any): UpdateButtonSortOrder {
    return UpdateButtonSortOrderFromJSONTyped(json, false);
}

export function UpdateButtonSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateButtonSortOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'buttons': json['buttons'] == null ? undefined : ((json['buttons'] as Array<any>).map(LaunchpadButtonSortOrderFromJSON)),
    };
}

export function UpdateButtonSortOrderToJSON(json: any): UpdateButtonSortOrder {
    return UpdateButtonSortOrderToJSONTyped(json, false);
}

export function UpdateButtonSortOrderToJSONTyped(value?: UpdateButtonSortOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buttons': value['buttons'] == null ? undefined : ((value['buttons'] as Array<any>).map(LaunchpadButtonSortOrderToJSON)),
    };
}

