/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersPagination } from './UsersPagination';
import {
    UsersPaginationFromJSON,
    UsersPaginationFromJSONTyped,
    UsersPaginationToJSON,
    UsersPaginationToJSONTyped,
} from './UsersPagination';
import type { UserRoleReference } from './UserRoleReference';
import {
    UserRoleReferenceFromJSON,
    UserRoleReferenceFromJSONTyped,
    UserRoleReferenceToJSON,
    UserRoleReferenceToJSONTyped,
} from './UserRoleReference';

/**
 * 
 * @export
 * @interface UserRoleReferences
 */
export interface UserRoleReferences {
    /**
     * 
     * @type {Array<UserRoleReference>}
     * @memberof UserRoleReferences
     */
    users?: Array<UserRoleReference>;
    /**
     * 
     * @type {UsersPagination}
     * @memberof UserRoleReferences
     */
    pagination?: UsersPagination;
}

/**
 * Check if a given object implements the UserRoleReferences interface.
 */
export function instanceOfUserRoleReferences(value: object): value is UserRoleReferences {
    return true;
}

export function UserRoleReferencesFromJSON(json: any): UserRoleReferences {
    return UserRoleReferencesFromJSONTyped(json, false);
}

export function UserRoleReferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleReferences {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserRoleReferenceFromJSON)),
        'pagination': json['pagination'] == null ? undefined : UsersPaginationFromJSON(json['pagination']),
    };
}

export function UserRoleReferencesToJSON(json: any): UserRoleReferences {
    return UserRoleReferencesToJSONTyped(json, false);
}

export function UserRoleReferencesToJSONTyped(value?: UserRoleReferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserRoleReferenceToJSON)),
        'pagination': UsersPaginationToJSON(value['pagination']),
    };
}

