/* tslint:disable */
/* eslint-disable */
/**
 * Bitly API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersPagination
 */
export interface UsersPagination {
    /**
     * 
     * @type {string}
     * @memberof UsersPagination
     */
    prev?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPagination
     */
    next?: string;
    /**
     * 
     * @type {number}
     * @memberof UsersPagination
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersPagination
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersPagination
     */
    size?: number;
}

/**
 * Check if a given object implements the UsersPagination interface.
 */
export function instanceOfUsersPagination(value: object): value is UsersPagination {
    return true;
}

export function UsersPaginationFromJSON(json: any): UsersPagination {
    return UsersPaginationFromJSONTyped(json, false);
}

export function UsersPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'prev': json['prev'] == null ? undefined : json['prev'],
        'next': json['next'] == null ? undefined : json['next'],
        'page': json['page'] == null ? undefined : json['page'],
        'total': json['total'] == null ? undefined : json['total'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function UsersPaginationToJSON(json: any): UsersPagination {
    return UsersPaginationToJSONTyped(json, false);
}

export function UsersPaginationToJSONTyped(value?: UsersPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prev': value['prev'],
        'next': value['next'],
        'page': value['page'],
        'total': value['total'],
        'size': value['size'],
    };
}

